### ISSUE TITLE
Unable to connect to video session after session disconnected

### ISSUE THREAD

**Issue by abhilashfancy** [OpenVidu/openvidu#111]
I am using the openvidu-js-node tutorial demo code. I have used v2.3.0 openvidu-server and app.js.
Suppose that after logging in the users are connected to a session named "test". They can perfectly communicate with each other. But after sometime the session gets disconnected automatically. Then after that when someone tries to connect to that session "test" nothing happens. And the log shows this error: 
```
Exception while sending message '{"method":"participantJoined","params":{"id":"ztnhe75tpthsotjb","metadata":"{\"clientData\":\"Ajay\"}%/%{\"serverData\":\"ajay_publisher\"}"},"jsonrpc":"2.0"}' to websocket with native sessionId '9'
 	at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.sendRequestWebSocket(WebSocketServerSession.java:120)
 	at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.access$000(WebSocketServerSession.java:48)
 	at org.kurento.jsonrpc.internal.ws.WebSocketServerSession$1.internalSendRequest(WebSocketServerSession.java:72)
 	at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendRequest(JsonRpcRequestSenderHelper.java:75)
 	at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendNotification(JsonRpcRequestSenderHelper.java:156)
 	at org.kurento.jsonrpc.internal.server.ServerSession.sendNotification(ServerSession.java:121)
 	at io.openvidu.server.rpc.RpcNotificationService.sendNotification(RpcNotificationService.java:98)
 	at io.openvidu.server.core.SessionEventsHandler.onParticipantJoined(SessionEventsHandler.java:140)
 	at io.openvidu.server.kurento.core.KurentoSessionManager.joinRoom(KurentoSessionManager.java:105)
 	at io.openvidu.server.rpc.RpcHandler.joinRoom(RpcHandler.java:183)
 	at io.openvidu.server.rpc.RpcHandler.handleRequest(RpcHandler.java:102)
 	at org.kurento.jsonrpc.internal.JsonRpcHandlerManager.handleRequest(JsonRpcHandlerManager.java:128)
 	at org.kurento.jsonrpc.internal.server.ProtocolManager$3.run(ProtocolManager.java:218)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 	at java.lang.Thread.run(Thread.java:748)
 Caused by: java.lang.IllegalStateException: The WebSocket session [9] has been closed and no method (apart from close()) may be called on a closed session
 	at org.apache.tomcat.websocket.WsSession.checkState(WsSession.java:803)
 	at org.apache.tomcat.websocket.WsSession.getBasicRemote(WsSession.java:446)
 	at org.springframework.web.socket.adapter.standard.StandardWebSocketSession.sendTextMessage(StandardWebSocketSession.java:197)
 	at org.springframework.web.socket.adapter.AbstractWebSocketSession.sendMessage(AbstractWebSocketSession.java:104)
 	at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.sendRequestWebSocket(WebSocketServerSession.java:117)
 	... 15 common frames omitted
```

**Comment by micaelgallego** [comment]
It seems websocket connection is closed for some reason.

Maybe you can use openvidu server located in demos.openvidu.io to see if is
a problem with your client or with the server installation.

Regards

**Comment by ajay01994** [comment]
Same issue here, anyone who can address it or has got some results on it?

**Comment by oisnot** [comment]
Sounds like the same problem as perhaps https://github.com/OpenVidu/openvidu/issues/115 .

User times out from openvidu server and as last user channel is closed. 
But node still has session as active in mapSession. 

So node tries to join instead of creating channel.

**Comment by pabloFuente** [comment]
Closing for inactivity
