### ISSUE TITLE
Cloudformation looks unstable by AWS Region

### ISSUE THREAD

**Issue by krish-dev** [OpenVidu/openvidu#135]
Cloud formation does not work with `AWS Asia Pacific (Sydney) [ap-southeast-2]` 

- AWS Region: Asia Pacific (Sydney) [ap-southeast-2]
- Instance Type: c5.2xlarge
- Log: [cloud-init-output.log](https://github.com/OpenVidu/openvidu/files/2533711/cloud-init-output.log) and [cloud-init.log](https://github.com/OpenVidu/openvidu/files/2533731/cloud-init.log)

**Comment by nordri** [comment]
Hi!
I just have deployed in that region and works fine.
OpenVidu can be deployed in all regions.
Cheers

**Comment by krish-dev** [comment]
Do you tried with same instance c5.2xlarge? 3 times fails again and again. Did you check the cloud-init.log

**Comment by nordri** [comment]
With that instance type there's a timeout (wonder why) but the app ends up and ready.
Do you try with another type?
>I think as per log we don't have any issue with putting crt and key info
agree with that.
Cheers

**Comment by krish-dev** [comment]
If you check my log `cloud-init-output.log` same behaviour for me also. Then I looked into the `cloud-init.log` and found log which not looks good. I think you should have a look it once. 

yes I tried with Singapore region with m5.xlarge and it works.

**Comment by krish-dev** [comment]
I'm talking about this error

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 843, in runparts
    subp(prefix + [exe_path], capture=False)
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 2035, in subp
    cmd=args)
cloudinit.util.ProcessExecutionError: Unexpected error while running command.
Command: ['/var/lib/cloud/instance/scripts/part-001']
Exit code: 1
Reason: -
Stdout: -
Stderr: -
2018-10-31 06:18:47,493 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2018-10-31 06:18:47,494 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: FAIL: running config-scripts-user with frequency once-per-instance
2018-10-31 06:18:47,494 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
2018-10-31 06:18:47,494 - util.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cloudinit/stages.py", line 806, in _run_modules
    freq=freq)
  File "/usr/lib/python3/dist-packages/cloudinit/cloud.py", line 54, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python3/dist-packages/cloudinit/helpers.py", line 188, in run
    return (True, results)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/cloudinit/helpers.py", line 76, in lock
    yield self._acquire(name, freq)
  File "/usr/lib/python3/dist-packages/cloudinit/helpers.py", line 187, in run
    results = functor(*args)
  File "/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py", line 45, in handle
    util.runparts(runparts_path)
  File "/usr/lib/python3/dist-packages/cloudinit/util.py", line 850, in runparts
    % (len(failed), len(attempted)))
RuntimeError: Runparts: 1 failures in 1 attempted commands
```

**Comment by krish-dev** [comment]
Hi @nordri 
Any news regarding this issue?

**Comment by nordri** [comment]
Hi @krish-dev 
I'm afraid not. There's something weird with that Instance type because I tried in my zone and still getting a timeout even though the app is ready.
