### ISSUE TITLE
Getting started with OpenVidu: 409 error joining a session

### ISSUE THREAD

**Issue by ashleydavis** [OpenVidu/openvidu#157]
Hi, OpenVidu looks really amazing and I'm trying to figure out how to get started with it.

To learn it I've built an example based on the OpenVidu Hello World example. Eventually I want to do more sophisticated things with OpenVidu but I'm struggling with the basic setup and so I haven't got beyond that.

If you can help me get started I'll be happy to contribute a more sophisticated example to your community.

I have my example in GitHub: [https://github.com/ashleydavis/open-vidu-example](https://github.com/ashleydavis/open-vidu-example)

There's some instructions there on how to boot the example using Vagrant or Docker-Compose (depending on your platform).

I'm testing it on a Windows PC, but under an Ubuntu VM and then booting the system using Docker-Compose.

Once I start the system I load up two instances of the web page on the same PC then I click the button to join the default session "Session A". 

I can see video displayed in each web page for the "YOU" section although the second web page seems unable to join the session and so I don't see anything displayed in the "OTHERS" section. 

The second web page is getting a 409 error in response to the HTTP POST api/session request:

![http post error](https://user-images.githubusercontent.com/625126/49843084-a323e700-fe09-11e8-9d8e-822fd19be1b6.png)

Any idea what I'm doing wrong here? 

I've also attempted to enable recording in this example (which I haven't been able to get working) - I'm not sure if that's related to HTTP POST problem or not.

**Comment by pabloFuente** [comment]
409 error is not a problem. As you can see in HTTP responses section here in [REST API docs](https://openvidu.io/docs/reference-docs/REST-API/#post-apisessions), when performing a POST operation to `/api/sessions`, 409 message states that the session you are trying to initialize with certain `customSessionId` is already created and ready to be used to create tokens (`POST /api/tokens`)

**Comment by ashleydavis** [comment]
Thanks for your quick response.

@micaelgallego This was the basic tutorial! After a few days trying to figure it out I'm pretty much stumped. 

It was pretty simple already, but I've taken care to remove all customization and I've recopied the assets from the Hello World example just to be sure they are 100% the same as the tutorial.

The OpenVidu server is running in a Docker container under an Ubuntu Vagrant VM (as this seems to be the  most convenient way to book the system under Windows). I also have it running in the cloud on an Ubuntu VM on Azure - but that's not easy to debug, hence the local setup.

I also have a Terraform script I'm using to deploy to Azure, so this can be quite a good and easy to boot example for you guys if you can help me get it working :)

@pabloFuente Ok so 409  isn't a problem. There still seems to be a problem though.

Now that I've simplified I have an application start up error as follows:

openvidu-server-kms    | 2018-12-12 09:48:49,108 DEBG 'openvidu-server' stdout output:
openvidu-server-kms    | [ERROR] 2018-12-12 09:48:49,107 [main] org.springframework.boot.SpringApplication (reportFailure) - Application startup failed
openvidu-server-kms    | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sessionRestController': Unsatisfied dependency expressed through field 'sessionManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sessionManager': Unsatisfied dependency expressed through field 'kcProvider'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kmsManager' defined in io.openvidu.server.OpenViduServer: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.openvidu.server.kurento.KurentoClientProvider]: Factory method 'kmsManager' threw exception; nested exception is org.kurento.commons.exception.KurentoException: Exception connecting to KMS

[I've committed the full log to the repo](https://github.com/ashleydavis/open-vidu-example/blob/master/system.log).

**Comment by pabloFuente** [comment]
That error shows up if OpenVidu Server cannot connect to Kurento Media Server.

How are you running OpenVidu Server? (the exact docker command you are using)

**Comment by ashleydavis** [comment]
This the configuration from my Docker-Compose file:

```
  openvidu-server-kms:
    image: openvidu/openvidu-server-kms:latest
    container_name: openvidu-server-kms
    ports:
     - "4443:4443"
    environment:
     - openvidu.secret=MY_SECRET
     - openvidu.publicurl=http://127.0.0.1:8000
    restart: always

```

**Comment by pabloFuente** [comment]
So you are trying to configure your own custom development setup for OpenVidu by using docker-compose. Why do you do that? Tutorials recommend to directly use this docker container:

```
docker run -p 4443:4443 --rm -e openvidu.secret=MY_SECRET -e openvidu.publicurl=https://OPENVIDU_SERVER_IP_ACCESSIBLE_TO_YOUR_APPLICATION:4443/ openvidu/openvidu-server-kms:2.6.0
```

**Comment by ashleydavis** [comment]
@pabloFuente My example is setup to be easily bootable. I spend a couple of hours preparing this so that you'd have 1-3 commands to run to boot up the Hello World example in a completely repeatable way (and I mean repeatable by people who are new to your platform).

**Comment by ashleydavis** [comment]
I've taken great care to replicate your official Hello World setup for myself.

Granted, this is probably broken due to my own incompetence, but I'm pretty much at the end of the road with it. After several days of trying to figure this out on my own I've reached out to you.

The only other option was to crack open your Java code and start debugging, but that's outside my skill set so if I can't get this Hello World sample working I'm probably just going to drop it

It seems great, but if I can't get hello world working I haven't got much hope of doing more sophisticated things with it.

**Comment by pabloFuente** [comment]
Tutorials are not broken. Our CI system says they are ok.
The problem you are experiencing is something really weird. OpenVidu Server is not able to connect to KMS, but both of them are perfectly wrapped inside docker container `openvidu/openvidu-server-kms`. This must be surely something related to the way you are running the container. I don't know if it's a Vagrant VM thing, a misconfiguration of docker-compose files or something else. Let's recap: if you perform the same steps as stated here.... https://openvidu.io/docs/tutorials/openvidu-hello-world/

... you are not able to successfully run the tutorial?

**Comment by ashleydavis** [comment]
I'm going to destroy and rebuild my Ubuntu 16 VM, but just before I do that...

If I run the command `docker run -p 4443:4443 --rm -e openvidu.secret=MY_SECRET openvidu/openvidu-server-kms:2.6.0` on a fresh Ubuntu VM you would expect that to work right and that the server should start correctly and without error?

That's the command that I have copied directly from [](https://openvidu.io/docs/tutorials/openvidu-hello-world/).

**Comment by ashleydavis** [comment]
The VM is rebuilding now. I just wanted to check if the exact Hello World docker command works on a fresh install or if it has the same problem. I'll report back once it has completed.

**Comment by pabloFuente** [comment]
Yeah, that's what I'm exactly asking :)

**Comment by ashleydavis** [comment]
I've rebuild the VM. It took a while to download updates and the Docker image.

But then same error...

If you'd like I could prepare a slightly simpler Vagrant box that demonstrates this problem?

2018-12-12 11:06:41,652 DEBG 'openvidu-server' stdout output:
[ERROR] 2018-12-12 11:06:41,650 [main] org.springframework.boot.SpringApplication (reportFailure) - Application startup failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sessionRestController': Unsatisfied dependency expressed through field 'sessionManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sessionManager': Unsatisfied dependency expressed through field 'kcProvider'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kmsManager' defined in io.openvidu.server.OpenViduServer: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.openvidu.server.kurento.KurentoClientProvider]: Factory method 'kmsManager' threw exception; nested exception is org.kurento.commons.exception.KurentoException: Exception connecting to KMS
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:592)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:370)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1219)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)

**Comment by pabloFuente** [comment]
It's not. I have just tested it on my own Ubuntu machine and it works just fine.

I repeat what I said earlier: this is not a problem with any tutorial, this is a problem with OpenVidu Server not being able to connect to Kurento Media Server inside container `openvidu/openvidu-server-kms`. So OpenVidu is not even running. No tutorial or app will be able to use it before it is launched ok.

The exact command you provided: `docker run -p 4443:4443 --rm -e openvidu.secret=MY_SECRET openvidu/openvidu-server-kms:2.6.0` works fine for me right now in an Ubuntu machine and in a Mac OS machine (both not virtualized). OpenVidu is launched fine and apps are able to connect to it.

If you provide instructions for me on how to run you Vagrant set up on Windows I can try it and see if the same happens to me.

**Comment by ashleydavis** [comment]
There's instruction in the readme: https://github.com/ashleydavis/open-vidu-example

It's essentially this:

```
cd the-repo
vagrant up
vagrant ssh
cd /vagrant
docker run -p 4443:4443 --rm -e openvidu.secret=MY_SECRET openvidu/openvidu-server-kms:2.6.0
```

Thanks for looking into it.

**Comment by ashleydavis** [comment]
Thanks for your help.

I've tried it again and I no longer see the connection problem. That might have been an temporary/intermittent problem. 

Hopefully this allows me to get back to solving the original problem. I'll keep you posted.

**Comment by keshavkaul** [comment]
@pabloFuente I'm facing the same error. A minute back, it was working fine, and then suddenly our app stopped working. I restarted the server but I see this Error:

I followed the ubuntu server deployment - https://openvidu.io/docs/deployment/deploying-ubuntu/

```
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
[ERROR] 2019-03-05 14:19:55,375 [main] org.springframework.boot.SpringApplication (reportFailure) - Application startup failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sessionRestController': Unsatisfied dependency expressed through field 'sessionManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sessionManager': Unsatisfied dependency expressed through field 'kcProvider'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kmsManager' defined in io.openvidu.server.OpenViduServer: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.openvidu.server.kurento.KurentoClientProvider]: Factory method 'kmsManager' threw exception; nested exception is org.kurento.commons.exception.KurentoException: Exception connecting to KMS
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:592)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:370)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1219)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:754)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
	at io.openvidu.server.OpenViduServer.main(OpenViduServer.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:521)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sessionManager': Unsatisfied dependency expressed through field 'kcProvider'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kmsManager' defined in io.openvidu.server.OpenViduServer: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.openvidu.server.kurento.KurentoClientProvider]: Factory method 'kmsManager' threw exception; nested exception is org.kurento.commons.exception.KurentoException: Exception connecting to KMS
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:592)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:370)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1219)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1131)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1059)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:589)
	... 27 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kmsManager' defined in io.openvidu.server.OpenViduServer: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.openvidu.server.kurento.KurentoClientProvider]: Factory method 'kmsManager' threw exception; nested exception is org.kurento.commons.exception.KurentoException: Exception connecting to KMS
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1128)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1022)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:512)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:207)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1131)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1059)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:589)
	... 40 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.openvidu.server.kurento.KurentoClientProvider]: Factory method 'kmsManager' threw exception; nested exception is org.kurento.commons.exception.KurentoException: Exception connecting to KMS
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 52 common frames omitted
Caused by: org.kurento.commons.exception.KurentoException: Exception connecting to KMS
	at org.kurento.client.KurentoClient.<init>(KurentoClient.java:258)
	at org.kurento.client.KurentoClient.create(KurentoClient.java:128)
	at org.kurento.client.KurentoClient.create(KurentoClient.java:121)
	at io.openvidu.server.kurento.kms.FixedOneKmsManager.<init>(FixedOneKmsManager.java:33)
	at io.openvidu.server.kurento.kms.FixedOneKmsManager.<init>(FixedOneKmsManager.java:28)
	at io.openvidu.server.OpenViduServer.kmsManager(OpenViduServer.java:109)
	at io.openvidu.server.OpenViduServer$$EnhancerBySpringCGLIB$$934520ce.CGLIB$kmsManager$0(<generated>)
	at io.openvidu.server.OpenViduServer$$EnhancerBySpringCGLIB$$934520ce$$FastClassBySpringCGLIB$$f98c12d0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
	at io.openvidu.server.OpenViduServer$$EnhancerBySpringCGLIB$$934520ce.kmsManager(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 53 common frames omitted
Caused by: org.kurento.jsonrpc.JsonRpcException: [KurentoClient]  Exception connecting to WebSocket server ws://localhost:8888/kurento
	at org.kurento.jsonrpc.client.AbstractJsonRpcClientWebSocket.internalConnectIfNecessary(AbstractJsonRpcClientWebSocket.java:734)
	at org.kurento.jsonrpc.client.AbstractJsonRpcClientWebSocket.connectIfNecessary(AbstractJsonRpcClientWebSocket.java:846)
	at org.kurento.jsonrpc.client.AbstractJsonRpcClientWebSocket.connect(AbstractJsonRpcClientWebSocket.java:677)
	at org.kurento.client.KurentoClient.<init>(KurentoClient.java:250)
	... 68 common frames omitted
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8888
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:627)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:551)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:465)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by pabloFuente** [comment]
Your KMS is down. Try stopping openvidu-server and then restart KMS with `sudo service kurento-media-server restart`. Then you can launch again openvidu-server

**Comment by keshavkaul** [comment]
@pabloFuente Thanks for the quick response! I wonder why the server would crash? Will the error log help in locating the root cause?

**Comment by pabloFuente** [comment]
Sure, search for file `/var/log/kurento-media-server/errors.log`. Post its content here if you want.

**Comment by shivp017** [comment]
Bro 
u can directly write this in docker compose file .
 openvidu-server-kms:
    image: openvidu/openvidu-server-kms:latest
    container_name: openvidu-server-kms
    ports:
     - "4443:4443"
    environment:
     - openvidu.secret=MY_SECRET
     - openvidu.publicurl=https://localhost:4443/
    restart: always
