### ISSUE TITLE
Self Signed Certificates for openvidu server

### ISSUE THREAD

**Issue by oisnot** [OpenVidu/openvidu#180]
I need to edit one file in lib (such as node_modules/openvidu-node-client/lib/OpenVidu.js) and edit the require axios line to make it work with self signed certificate for dev server. (Editing Session.js works as well.)

```
const https = require("https");
var axios_1 = require("axios");
axios_1.default = axios_1.create({
  httpsAgent: new https.Agent({
    rejectUnauthorized: false
  })
});
```

Is it possible to add a method/function so I can add my own axios instance without editing files in node_modules?

**Comment by pabloFuente** [comment]
So you are getting authorization errors when performing REST operations to openvidu-server through openvidu-node-client because of a self-signed certificate, am I right?
I have never seen that issue and my development setup is actually using self-signed certificates too. openvidu-node-client does not fail when communicating with my openvidu-server dev instance even though it has an insecure certificate. Do you know how can I replicate this issue?

**Comment by oisnot** [comment]
I'm running openvidu kms server in a docker container. 

> 93cb9d1ff63e        openvidu/openvidu-server-kms:2.6.0   "/usr/bin/supervisord"   2 days ago          Up 2 days           8888/tcp, 0.0.0.0:4443->4443/tcp, 9091/tcp   goofy_jepsen

I added this to the top of Session.js and a few debug lines. 

> const debug = require('debug')('bbvs:openvidu:sessions');

Start node with this:
```
DEBUG=* OPENVIDU_URL=https://10.10.2.109:4443 OPENVIDU_SECRET=PASS npm start
```

Node error printout from console, edited base64 encoded pass string: 
```
  express:router dispatching POST /openvidu/token +92ms
  express:router query  : /openvidu/token +0ms
  express:router expressInit  : /openvidu/token +0ms
  express:router favicon  : /openvidu/token +0ms
  express:router logger  : /openvidu/token +0ms
  express:router jsonParser  : /openvidu/token +0ms
  body-parser:json content-type "application/json" +0ms
  body-parser:json content-encoding "identity" +1ms
  body-parser:json read body +0ms
  body-parser:json parse body +0ms
  body-parser:json parse json +0ms
  express:router urlencodedParser  : /openvidu/token +0ms
  body-parser:urlencoded body already parsed +0ms
  express:router cookieParser  : /openvidu/token +0ms
  express:router jsonParser  : /openvidu/token +0ms
  body-parser:json body already parsed +0ms
  express:router serveStatic  : /openvidu/token +1ms
  express:router serveStatic  : /openvidu/token +0ms
  express:router session  : /openvidu/token +0ms
  express-session fetching V6A9HHg6DiP6OJo25A-nMP-8crMNUj0K +0ms
  express-session session found +2ms
  express:router initialize  : /openvidu/token +0ms
  express:router authenticate  : /openvidu/token +0ms
  mquery findOne users { _id: 5c4720fb80f381276431ea70 } { fields: {} } +1ms
  express:router <anonymous>  : /openvidu/token +3ms
  express:router router  : /openvidu/token +0ms
  express:router dispatching POST /openvidu/token +0ms
  express:router trim prefix (/openvidu) from url /openvidu/token +1ms
  express:router router /openvidu : /openvidu/token +0ms
  express:router dispatching POST /token +0ms
  bbvs:openvidu:routes Getting a token. Session name:  trening +0ms
  bbvs:openvidu:sessions Setting up axios +1ms
  follow-redirects options { protocol: 'https:',
  maxRedirects: 21,
  maxBodyLength: 10485760,
  path: '/api/sessions',
  method: 'post',
  headers:
   { Accept: 'application/json, text/plain, */*',
     'Content-Type': 'application/json',
     Authorization: 'Basic ***********',
     'User-Agent': 'axios/0.18.0',
     'Content-Length': 129 },
  agent: undefined,
  auth: undefined,
  hostname: '10.10.2.109',
  port: '4443',
  nativeProtocols:
   { 'http:':
      { _connectionListener: [Function: connectionListener],
        METHODS: [Array],
        STATUS_CODES: [Object],
        Agent: [Function],
        ClientRequest: [Function],
        globalAgent: [Agent],
        IncomingMessage: [Function],
        OutgoingMessage: [Function],
        Server: [Function],
        ServerResponse: [Function],
        createServer: [Function: createServer],
        get: [Function: get],
        request: [Function: request],
        maxHeaderSize: [Getter] },
     'https:':
      { Agent: [Function],
        globalAgent: [Agent],
        Server: [Function],
        createServer: [Function: createServer],
        get: [Function: get],
        request: [Function: request] } } } +0ms
  express:router dispatching GET /favicon.ico +6ms
  express:router query  : /favicon.ico +0ms
  express:router expressInit  : /favicon.ico +1ms
  express:router favicon  : /favicon.ico +0ms
  bbvs:openvidu:sessions Response error! +16ms
  bbvs:openvidu:sessions The request was made but no response was received Writable {
  _writableState:
   WritableState {
     objectMode: false,
     highWaterMark: 16384,
     finalCalled: false,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     destroyed: false,
     decodeStrings: true,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: true,
     bufferProcessing: false,
     onwrite: [Function: bound onwrite],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: false,
     errorEmitted: false,
     emitClose: true,
     bufferedRequestCount: 0,
     corkedRequestsFree:
      { next: null,
        entry: null,
        finish: [Function: bound onCorkedFinish] } },
  writable: true,
  _events:
   [Object: null prototype] {
     response: [Function: handleResponse],
     error: [Function: handleRequestError] },
  _eventsCount: 2,
  _maxListeners: undefined,
  _options:
   { protocol: 'https:',
     maxRedirects: 21,
     maxBodyLength: 10485760,
     path: '/api/sessions',
     method: 'post',
     headers:
      { Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json',
        Authorization: 'Basic *********',
        'User-Agent': 'axios/0.18.0',
        'Content-Length': 129 },
     agent: undefined,
     auth: undefined,
     hostname: '10.10.2.109',
     port: '4443',
     nativeProtocols: { 'http:': [Object], 'https:': [Object] },
     pathname: '/api/sessions' },
  _redirectCount: 0,
  _redirects: [],
  _requestBodyLength: 129,
  _requestBodyBuffers:
   [ { data:
        <Buffer 7b 22 6d 65 64 69 61 4d 6f 64 65 22 3a 22 52 4f 55 54 45 44 22 2c 22 72 65 63 6f 72 64 69 6e 67 4d 6f 64 65 22 3a 22 4d 41 4e 55 41 4c 22 2c 22 64 65 ... >,
       encoding: undefined } ],
  _onNativeResponse: [Function],
  _currentRequest:
   ClientRequest {
     _events:
      [Object: null prototype] {
        response: [Function],
        socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        timeout: [Function] },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: true,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: null,
     _hasBody: true,
     _trailer: '',
     finished: false,
     _headerSent: true,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: '10.10.2.109',
        alpnProtocol: false,
        authorized: false,
        authorizationError: 'DEPTH_ZERO_SELF_SIGNED_CERT',
        encrypted: true,
        _events: [Object],
        _eventsCount: 8,
        connecting: false,
        _hadError: true,
        _handle: null,
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: false,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 3803,
        [Symbol(lastWriteQueueSize)]: 376,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 376,
        [Symbol(connect-options)]: [Object] },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: '10.10.2.109',
        alpnProtocol: false,
        authorized: false,
        authorizationError: 'DEPTH_ZERO_SELF_SIGNED_CERT',
        encrypted: true,
        _events: [Object],
        _eventsCount: 8,
        connecting: false,
        _hadError: true,
        _handle: null,
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: false,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 3803,
        [Symbol(lastWriteQueueSize)]: 376,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 376,
        [Symbol(connect-options)]: [Object] },
     _header:
      'POST /api/sessions HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/json\r\nAuthorization: Basic ********\r\nUser-Agent: axios/0.18.0\r\nContent-Length: 129\r\nHost: 10.10.2.109:4443\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: 'POST',
     path: '/api/sessions',
     _ended: false,
     res: null,
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable: [Circular],
     [Symbol(isCorked)]: false,
     [Symbol(outHeadersKey)]:
      [Object: null prototype] {
        accept: [Array],
        'content-type': [Array],
        authorization: [Array],
        'user-agent': [Array],
        'content-length': [Array],
        host: [Array] } },
  _currentUrl: 'https://10.10.2.109:4443/api/sessions' } +0ms
  bbvs:openvidu:commands Error creating session in createOrGetSession  code  undefined message  [object Object] stack  Error: [object Object]
    at /home/oistein/code/gtdocker/node_modules/openvidu-node-client/lib/Session.js:435:28
    at process._tickCallback (internal/process/next_tick.js:68:7) error object  Error: [object Object] error properties  [ 'stack', 'message' ] +2ms
  bbvs:openvidu:routes Error getting token  Error: [object Object] +0ms
  express-session touching +0ms
  follow-redirects options { protocol: 'https:',
  maxRedirects: 21,
  maxBodyLength: 10485760,
  path: '/api/sessions',
  method: 'get',
  headers:
   { Accept: 'application/json, text/plain, */*',
     Authorization: 'Basic ************',
     'User-Agent': 'axios/0.18.0' },
  agent: undefined,
  auth: undefined,
  hostname: '10.10.2.109',
  port: '4443',
  nativeProtocols:
   { 'http:':
      { _connectionListener: [Function: connectionListener],
        METHODS: [Array],
        STATUS_CODES: [Object],
        Agent: [Function],
        ClientRequest: [Function],
        globalAgent: [Agent],
        IncomingMessage: [Function],
        OutgoingMessage: [Function],
        Server: [Function],
        ServerResponse: [Function],
        createServer: [Function: createServer],
        get: [Function: get],
        request: [Function: request],
        maxHeaderSize: [Getter] },
     'https:':
      { Agent: [Function],
        globalAgent: [Agent],
        Server: [Function],
        createServer: [Function: createServer],
        get: [Function: get],
        request: [Function: request] } } } +23ms
  express-session touched +5ms
  morgan log request +1ms
POST /openvidu/token 500 40.005 ms - -
Writable {
  _writableState:
   WritableState {
     objectMode: false,
     highWaterMark: 16384,
     finalCalled: false,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     destroyed: false,
     decodeStrings: true,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: true,
     bufferProcessing: false,
     onwrite: [Function: bound onwrite],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: false,
     errorEmitted: false,
     emitClose: true,
     bufferedRequestCount: 0,
     corkedRequestsFree:
      { next: null,
        entry: null,
        finish: [Function: bound onCorkedFinish] } },
  writable: true,
  _events:
   [Object: null prototype] {
     response: [Function: handleResponse],
     error: [Function: handleRequestError] },
  _eventsCount: 2,
  _maxListeners: undefined,
  _options:
   { protocol: 'https:',
     maxRedirects: 21,
     maxBodyLength: 10485760,
     path: '/api/sessions',
     method: 'get',
     headers:
      { Accept: 'application/json, text/plain, */*',
        Authorization: 'Basic ***********',
        'User-Agent': 'axios/0.18.0' },
     agent: undefined,
     auth: undefined,
     hostname: '10.10.2.109',
     port: '4443',
     nativeProtocols: { 'http:': [Object], 'https:': [Object] },
     pathname: '/api/sessions' },
  _redirectCount: 0,
  _redirects: [],
  _requestBodyLength: 0,
  _requestBodyBuffers: [],
  _onNativeResponse: [Function],
  _currentRequest:
   ClientRequest {
     _events:
      [Object: null prototype] {
        response: [Function],
        socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        timeout: [Function] },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: false,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 0,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: '10.10.2.109',
        alpnProtocol: false,
        authorized: false,
        authorizationError: 'DEPTH_ZERO_SELF_SIGNED_CERT',
        encrypted: true,
        _events: [Object],
        _eventsCount: 8,
        connecting: false,
        _hadError: true,
        _handle: null,
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: false,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 3839,
        [Symbol(lastWriteQueueSize)]: 193,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 193,
        [Symbol(connect-options)]: [Object] },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: '10.10.2.109',
        alpnProtocol: false,
        authorized: false,
        authorizationError: 'DEPTH_ZERO_SELF_SIGNED_CERT',
        encrypted: true,
        _events: [Object],
        _eventsCount: 8,
        connecting: false,
        _hadError: true,
        _handle: null,
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: false,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(res)]: [TLSWrap],
        [Symbol(asyncId)]: 3839,
        [Symbol(lastWriteQueueSize)]: 193,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 193,
        [Symbol(connect-options)]: [Object] },
     _header:
      'GET /api/sessions HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nAuthorization: Basic *****************\r\nUser-Agent: axios/0.18.0\r\nHost: 10.10.2.109:4443\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: 'GET',
     path: '/api/sessions',
     _ended: false,
     res: null,
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable: [Circular],
     [Symbol(isCorked)]: false,
     [Symbol(outHeadersKey)]:
      [Object: null prototype] {
        accept: [Array],
        authorization: [Array],
        'user-agent': [Array],
        host: [Array] } },
  _currentUrl: 'https://10.10.2.109:4443/api/sessions' }
```

This is from my openvidu module:
```
commands.createOrGetSession = (name) => {
  return new Promise(function (resolve, reject) {
    if (commands.isMapSession(name)) {
      let session = commands.getMapSession(name);
      resolve(session);
      return;
    }

    myOV.createSession()
      .then(session => {
        commands.setMapSession(name, session);
        resolve(session);
      }).catch(error => {
        debug("Error creating session in createOrGetSession ",
          "code ", error.code,
          "message ", error.message.toString(),
          "stack ", error.stack,
          "error object ", error.toString(),
          "error properties ", Object.getOwnPropertyNames(error)

        );
        reject(error);
      });
  });
};

commands.joinSession = (session, name, data, role = OpenViduRole.PUBLISHER) => {
  return new Promise(function (resolve, reject) {
    debug("Generating token ", {data, role});
    session.generateToken({data, role})
      .then(token => {
        debug("Store the new token in the collection of tokens", token.toString());
        commands.addMapSessionToken(name, token);

        resolve(token);
        return;
      })
      .catch(error => {
        debug("Error generating Map Session Token", error.toString());
        console.error(error);
        reject(error);
        return;
      });
  });
};
```

This is from openvidu route:
```
/ Get token (add new user to session)
router.post('/token', auth.user, (req, res) => {
  let sessionName = req.body.sessionName;

  // Role associated to this user
  //var role = users.find(u => (u.user === req.session.loggedUser)).role;
  let role = openvidu.OpenViduRole.PUBLISHER;

  // Optional data to be passed to other users when this user connects to the video-call
  // In this case, a JSON with the value we stored in the req.session object on login
  let serverData = JSON.stringify({ serverData: req.user.firstName });

  debug("Getting a token. Session name: ", sessionName);

  let success = (token) => {
    res.status(200).send({
        token
    });
  };

  let failure = (error) => {
    debug("Error getting token ", error.toString());
    res.status(500).send();
  };

  let sessionSuccess = (session) => {
    return openvidu.joinSession(session, sessionName, serverData, role);
  };

  openvidu.createOrGetSession(sessionName)
    .then(sessionSuccess)
    .then(success)
    .catch(failure);
});
```

**Comment by pabloFuente** [comment]
Maybe this simple post will solve your problem in your specific dev setup: https://gsferreira.com/archive/2014/12/overcome-the-depth_zero_self_signed_cert-on-nodejs/

Give that a try and tell us here if it worked.

Regards

**Comment by oisnot** [comment]
Just adding this before npm start with all the other commands works for dev. 

```
DEBUG=* NODE_TLS_REJECT_UNAUTHORIZED=0 npm start
```

Thank you for that. Should come in handy in other projects as well. :)
