### ISSUE TITLE
Participant connection error ghosting channel

### ISSUE THREAD

**Issue by oisnot** [OpenVidu/openvidu#206]
A publisher in channel is still "connected" even though it disconnected. 

```
[INFO] 2019-02-18 16:07:48,583 [8080-exec-10] io.openvidu.server.rpc.RpcHandler (afterConnectionEstablished) - After connection established for WebSocket session: bagm4gojpdt6e7ncgef6c82u26
[INFO] 2019-02-18 16:07:48,587 [82u26-e23-t0] io.openvidu.server.core.Session (join) - SESSION trening: Added participant [participantPrivateId=bagm4gojpdt6e7ncgef6c82u26, participantPublicId=6osuvyqvsd9vs2rp, streaming=false]
[INFO] 2019-02-18 16:13:39,043 [kh0gl-e19-t0] io.openvidu.server.rpc.RpcNotificationService (showRpcConnections) - <PRIVATE_ID, RPC_CONNECTION>: {bs75ggci1r8gqm0r0bvllu658u=io.openvidu.server.rpc.RpcConnection@1261debf, bagm4gojpdt6e7ncgef6c82u26=io.openvidu.server.rpc.RpcConnection@1ca62283, mjqmbokujlf34561cem869h5st=io.openvidu.server.rpc.RpcConnection@1899b5cf, 6pvalpf2o0j2qk3nubgjvn0ea0=io.openvidu.server.rpc.RpcConnection@5d9b28b8}
[INFO] 2019-02-18 16:19:04,729 [g4kiv-e24-t0] io.openvidu.server.rpc.RpcNotificationService (showRpcConnections) - <PRIVATE_ID, RPC_CONNECTION>: {bs75ggci1r8gqm0r0bvllu658u=io.openvidu.server.rpc.RpcConnection@1261debf, bagm4gojpdt6e7ncgef6c82u26=io.openvidu.server.rpc.RpcConnection@1ca62283, mjqmbokujlf34561cem869h5st=io.openvidu.server.rpc.RpcConnection@1899b5cf, 6pvalpf2o0j2qk3nubgjvn0ea0=io.openvidu.server.rpc.RpcConnection@5d9b28b8}
[ERROR] 2019-02-18 16:19:53,476 [-8080-exec-7] io.openvidu.server.rpc.RpcHandler (handleTransportError) - Transport exception for WebSocket session: bagm4gojpdt6e7ncgef6c82u26 - Exception: {}
[ERROR] 2019-02-18 16:19:53,478 [-8080-exec-7] io.openvidu.server.rpc.RpcHandler (handleUncaughtException) - Uncaught exception for WebSocket session: bagm4gojpdt6e7ncgef6c82u26 - Exception: {}
[INFO] 2019-02-18 16:20:03,483 [kScheduler-1] io.openvidu.server.rpc.RpcHandler (afterConnectionClosed) - After connection closed for WebSocket session: bagm4gojpdt6e7ncgef6c82u26 - Status: Connection reset by peer
[ERROR] 2019-02-18 16:21:26,306 [n0ea0-e21-t0] io.openvidu.server.rpc.RpcNotificationService (sendNotification) - Exception sending notification 'participantLeft': {"connectionId":"pwkr9t0vjvuskw0x","reason":"disconnect"} to participant with private id bagm4gojpdt6e7ncgef6c82u26
```

As you can see openvidu still tries to send it messages, and all new participants get a empty connection. 
```
[ERROR] 2019-02-20 13:43:44,166 [0pa1p-e33-t0] io.openvidu.server.rpc.RpcNotificationService (sendNotification) - Exception sending notification 'participantLeft': {"connectionId":"8exffefnwwwjlch4","reason":"disconnect"} to participant with private id bagm4gojpdt6e7ncgef6c82u26
[INFO] 2019-02-20 13:43:44,174 [0pa1p-e33-t0] io.openvidu.server.rpc.RpcNotificationService (showRpcConnections) - <PRIVATE_ID, RPC_CONNECTION>: {bagm4gojpdt6e7ncgef6c82u26=io.openvidu.server.rpc.RpcConnection@1ca62283, ubc11b9kpobnbnvhp59fani7fc=io.openvidu.server.rpc.RpcConnection@15b56cc5, 2qm0gg842peqh9lpqllsau98g5=io.openvidu.server.rpc.RpcConnection@ef594b1, j1v8u8e62kobd9h0b18slke984=io.openvidu.server.rpc.RpcConnection@1b728003, 20hq3sfqt7jhg53lok4qevfksa=io.openvidu.server.rpc.RpcConnection@307975b5}
```

Data from Chrome: 
![skjermdump fra 2019-02-20 14-58-17](https://user-images.githubusercontent.com/2698541/53096847-5c94ec00-3520-11e9-9121-a8b47523f502.png)

Another ghosted participant on the same channel:
```
[INFO] 2019-02-18 20:37:12,377 [-8080-exec-8] io.openvidu.server.rpc.RpcHandler (afterConnectionEstablished) - After connection established for WebSocket session: 20hq3sfqt7jhg53lok4qevfksa
[INFO] 2019-02-18 20:37:12,380 [vfksa-e27-t0] io.openvidu.server.core.Session (join) - SESSION trening: Added participant [participantPrivateId=20hq3sfqt7jhg53lok4qevfksa, participantPublicId=cacywdr41yfof7pw, streaming=false]
[ERROR] 2019-02-18 21:55:39,418 [-8080-exec-7] io.openvidu.server.rpc.RpcHandler (handleTransportError) - Transport exception for WebSocket session: 20hq3sfqt7jhg53lok4qevfksa - Exception: {}
[ERROR] 2019-02-18 21:55:39,418 [-8080-exec-7] io.openvidu.server.rpc.RpcHandler (handleUncaughtException) - Uncaught exception for WebSocket session: 20hq3sfqt7jhg53lok4qevfksa - Exception: {}
[INFO] 2019-02-18 21:55:49,421 [kScheduler-1] io.openvidu.server.rpc.RpcHandler (afterConnectionClosed) - After connection closed for WebSocket session: 20hq3sfqt7jhg53lok4qevfksa - Status: Connection reset by peer
[ERROR] 2019-02-19 06:47:34,399 [9h5st-e20-t0] io.openvidu.server.rpc.RpcNotificationService (sendNotification) - Exception sending notification 'participantLeft': {"connectionId":"cnvejqzhzqwbu9if","reason":"disconnect"} to participant with private id 20hq3sfqt7jhg53lok4qevfksa
[INFO] 2019-02-19 06:47:34,402 [9h5st-e20-t0] io.openvidu.server.rpc.RpcNotificationService (showRpcConnections) - <PRIVATE_ID, RPC_CONNECTION>: {bagm4gojpdt6e7ncgef6c82u26=io.openvidu.server.rpc.RpcConnection@1ca62283, 20hq3sfqt7jhg53lok4qevfksa=io.openvidu.server.rpc.RpcConnection@307975b5}
[ERROR] 2019-02-19 13:03:18,599 [vfn2u-e28-t0] io.openvidu.server.rpc.RpcNotificationService (sendNotification) - Exception sending notification 'participantJoined': {"id":"yp29xweptqfgxvv5","createdAt":1550581398595,"metadata":"{\"clientData\":\"Name\"}%/%{\"serverData\":\"Name\"}"} to participant with private id 20hq3sfqt7jhg53lok4qevfksa
```

**Comment by oisnot** [comment]
Tried to kick one ghost.

```
curl -X DELETE -H "Authorization: Basic $(echo -n "OPENVIDUAPP:PASS" | base64)" https://server/api/sessions/sessionid/connection/bagm4gojpdt6e7ncgef6c82u26
```

Server log:
```
2019-02-21T14:56:16.330014920Z [INFO] 2019-02-21 14:56:16,327 [8080-exec-10] io.openvidu.server.rest.SessionRestController (disconnectParticipant) - REST API: DELETE /api/sessions/sessionid/connection/bagm4gojpdt6e7ncgef6c82u26
2019-02-21T14:56:47.421407103Z 2019-02-21 14:56:47,420 DEBG 'openvidu-server' stdout output:
2019-02-21T14:56:47.421473707Z [INFO] 2019-02-21 14:56:47,408 [-8080-exec-1] io.openvidu.server.rest.SessionRestController (getSession) - REST API: GET /api/sessions/sessionid
```

After I asked for session info it ... did something. 

```
2019-02-21T14:57:50.247332295Z 2019-02-21 14:57:50,246 DEBG 'openvidu-server' stdout output:
2019-02-21T14:57:50.247436871Z [INFO] 2019-02-21 14:57:50,245 [kScheduler-1] io.openvidu.server.rpc.RpcHandler (afterConnectionClosed) - After connection closed for WebSocket session: ubc11b9kpobnbnvhp59fani7fc - Status: Close for not receive ping from client
2019-02-21T14:57:50.247486658Z [INFO] 2019-02-21 14:57:50,245 [kScheduler-1] io.openvidu.server.rpc.RpcNotificationService (closeRpcSession) - Closed session for participant with private id ubc11b9kpobnbnvhp59fani7fc
2019-02-21T14:57:50.247530244Z [INFO] 2019-02-21 14:57:50,246 [kScheduler-1] io.openvidu.server.rpc.RpcNotificationService (showRpcConnections) - <PRIVATE_ID, RPC_CONNECTION>: {bagm4gojpdt6e7ncgef6c82u26=io.openvidu.server.rpc.RpcConnection@1ca62283, 2qm0gg842peqh9lpqllsau98g5=io.openvidu.server.rpc.RpcConnection@ef594b1, 20hq3sfqt7jhg53lok4qevfksa=io.openvidu.server.rpc.RpcConnection@307975b5}
2019-02-21T14:57:50.247576234Z 
2019-02-21T14:57:50.248786568Z 2019-02-21 14:57:50,247 DEBG 'openvidu-server' stdout output:
2019-02-21T14:57:50.248839661Z [INFO] 2019-02-21 14:57:50,246 [kScheduler-1] io.openvidu.server.rpc.RpcHandler (afterConnectionClosed) - Evicting participant with private id ubc11b9kpobnbnvhp59fani7fc because of a network disconnection
2019-02-21T14:57:50.248895200Z [INFO] 2019-02-21 14:57:50,246 [kScheduler-1] io.openvidu.server.core.Session (leave) - PARTICIPANT fksxx207fxwz7ede: Leaving session trening
2019-02-21T14:57:50.248920998Z [INFO] 2019-02-21 14:57:50,246 [kScheduler-1] io.openvidu.server.kurento.core.KurentoParticipant (cancelReceivingMedia) - PARTICIPANT 6osuvyqvsd9vs2rp: cancel receiving media from fksxx207fxwz7ede
2019-02-21T14:57:50.248945160Z [WARN] 2019-02-21 14:57:50,246 [kScheduler-1] io.openvidu.server.kurento.core.KurentoParticipant (cancelReceivingMedia) - PARTICIPANT 6osuvyqvsd9vs2rp: Trying to cancel receiving video from user fksxx207fxwz7ede. But there is no such subscriber endpoint.
2019-02-21T14:57:50.248969498Z 
2019-02-21T14:57:50.250946292Z 2019-02-21 14:57:50,248 DEBG 'openvidu-server' stdout output:
2019-02-21T14:57:50.251024390Z [INFO] 2019-02-21 14:57:50,247 [kScheduler-1] io.openvidu.server.kurento.core.KurentoParticipant (cancelReceivingMedia) - PARTICIPANT uncs99dae5y6qqfw: cancel receiving media from fksxx207fxwz7ede
2019-02-21T14:57:50.251056115Z 
2019-02-21T14:57:50.251079440Z 2019-02-21 14:57:50,248 DEBG 'openvidu-server' stdout output:
2019-02-21T14:57:50.251102355Z [INFO] 2019-02-21 14:57:50,248 [kScheduler-1] io.openvidu.server.kurento.core.KurentoParticipant (cancelReceivingMedia) - PARTICIPANT uncs99dae5y6qqfw: stopped receiving media from fksxx207fxwz7ede in room trening
2019-02-21T14:57:50.251138665Z 
2019-02-21T14:57:50.251161719Z 2019-02-21 14:57:50,249 DEBG 'openvidu-server' stdout output:
2019-02-21T14:57:50.251184655Z [INFO] 2019-02-21 14:57:50,248 [kScheduler-1] io.openvidu.server.kurento.core.KurentoParticipant (cancelReceivingMedia) - PARTICIPANT cacywdr41yfof7pw: cancel receiving media from fksxx207fxwz7ede
2019-02-21T14:57:50.251208282Z [WARN] 2019-02-21 14:57:50,248 [kScheduler-1] io.openvidu.server.kurento.core.KurentoParticipant (cancelReceivingMedia) - PARTICIPANT cacywdr41yfof7pw: Trying to cancel receiving video from user fksxx207fxwz7ede. But there is no such subscriber endpoint.
2019-02-21T14:57:50.251232242Z 
2019-02-21T14:57:50.271366547Z 73:33:51.261841768     9 0x7f1b040020a0 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:1007:disconnect: Disconnecting 21aeeb4b-ab14-4564-900b-94c2eaa822e3_kurento.MediaPipeline/449d0f12-1932-4cff-8794-0e234e5030e7_kurento.PassThrough - fksxx207fxwz7ede_uncs99dae5y6qqfw_CAMERA_LCMFH params AUDIO default default
2019-02-21T14:57:50.271398793Z 
2019-02-21T14:57:50.271422320Z 2019-02-21 14:57:50,269 DEBG 'kms' stdout output:
2019-02-21T14:57:50.271448847Z 73:33:51.262371159     9 0x7f1b040020a0 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:1007:disconnect: Disconnecting 21aeeb4b-ab14-4564-900b-94c2eaa822e3_kurento.MediaPipeline/449d0f12-1932-4cff-8794-0e234e5030e7_kurento.PassThrough - fksxx207fxwz7ede_uncs99dae5y6qqfw_CAMERA_LCMFH params DATA default default
2019-02-21T14:57:50.271492207Z 73:33:51.262491282     9 0x7f1b040020a0 DEBUG   KurentoMediaElementImpl MediaElementImpl.cpp:1007:disconnect: Disconnecting 21aeeb4b-ab14-4564-900b-94c2eaa822e3_kurento.MediaPipeline/449d0f12-1932-4cff-8794-0e234e5030e7_kurento.PassThrough - fksxx207fxwz7ede_uncs99dae5y6qqfw_CAMERA_LCMFH params VIDEO default default
2019-02-21T14:57:50.271551163Z 
2019-02-21T14:57:50.271576349Z 2019-02-21 14:57:50,270 DEBG 'kms' stdout output:
2019-02-21T14:57:50.271599603Z 73:33:51.262998301     9 0x7f1b040020a0 DEBUG        KurentoMediaSet MediaSet.cpp:470:async_delete: Destroying WebRtcEndpoint -> 21aeeb4b-ab14-4564-900b-94c2eaa822e3_kurento.MediaPipeline/fa425406-9efb-4e9c-824a-21c8ee76b283_kurento.WebRtcEndpoint

2019-02-21T14:57:50.300332509Z [INFO] 2019-02-21 14:57:50,290 [kScheduler-1] io.openvidu.server.core.SessionManager (showTokens) - <SESSIONID, TOKENS>: {sessionid={}}
2019-02-21T14:57:50.300365483Z [ERROR] 2019-02-21 14:57:50,292 [kScheduler-1] io.openvidu.server.rpc.RpcNotificationService (sendNotification) - Exception sending notification 'participantLeft': {"connectionId":"fksxx207fxwz7ede","reason":"networkDisconnect"} to participant with private id 20hq3sfqt7jhg53lok4qevfksa
2019-02-21T14:57:50.300392339Z org.kurento.commons.exception.KurentoException: Exception while sending message '{"method":"participantLeft","params":{"connectionId":"fksxx207fxwz7ede","reason":"networkDisconnect"},"jsonrpc":"2.0"}' to websocket with native sessionId '19'
2019-02-21T14:57:50.300427333Z 	at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.sendRequestWebSocket(WebSocketServerSession.java:121)
2019-02-21T14:57:50.300481903Z 	at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.access$000(WebSocketServerSession.java:48)
2019-02-21T14:57:50.300518039Z 	at org.kurento.jsonrpc.internal.ws.WebSocketServerSession$1.internalSendRequest(WebSocketServerSession.java:72)
2019-02-21T14:57:50.300550458Z 	at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendRequest(JsonRpcRequestSenderHelper.java:75)
2019-02-21T14:57:50.300582838Z 	at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendNotification(JsonRpcRequestSenderHelper.java:156)
2019-02-21T14:57:50.300618046Z 	at org.kurento.jsonrpc.internal.server.ServerSession.sendNotification(ServerSession.java:121)
2019-02-21T14:57:50.300651782Z 	at io.openvidu.server.rpc.RpcNotificationService.sendNotification(RpcNotificationService.java:98)
2019-02-21T14:57:50.300685495Z 	at io.openvidu.server.core.SessionEventsHandler.onParticipantLeft(SessionEventsHandler.java:179)
2019-02-21T14:57:50.300718482Z 	at io.openvidu.server.kurento.core.KurentoSessionManager.leaveRoom(KurentoSessionManager.java:169)
2019-02-21T14:57:50.300751572Z 	at io.openvidu.server.kurento.core.KurentoSessionManager.evictParticipant(KurentoSessionManager.java:525)
2019-02-21T14:57:50.300775758Z 	at io.openvidu.server.rpc.RpcHandler.leaveRoomAfterConnClosed(RpcHandler.java:537)
2019-02-21T14:57:50.300798352Z 	at io.openvidu.server.rpc.RpcHandler.afterConnectionClosed(RpcHandler.java:586)
2019-02-21T14:57:50.300820742Z 	at org.kurento.jsonrpc.internal.JsonRpcHandlerManager.afterConnectionClosed(JsonRpcHandlerManager.java:65)
2019-02-21T14:57:50.300847278Z 	at org.kurento.jsonrpc.internal.server.ProtocolManager.closeSession(ProtocolManager.java:446)
2019-02-21T14:57:50.300870212Z 	at org.kurento.jsonrpc.internal.server.ProtocolManager$4.run(ProtocolManager.java:421)
2019-02-21T14:57:50.300892992Z 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
2019-02-21T14:57:50.300916087Z 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2019-02-21T14:57:50.300938402Z 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-02-21T14:57:50.300960721Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
2019-02-21T14:57:50.300983088Z 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
2019-02-21T14:57:50.301005314Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2019-02-21T14:57:50.301027615Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2019-02-21T14:57:50.301050044Z 	at java.lang.Thread.run(Thread.java:748)
2019-02-21T14:57:50.301072261Z Caused by: java.lang.IllegalStateException: The WebSocket session [19] has been closed and no method (apart from close()) may be called on a closed session
2019-02-21T14:57:50.301095224Z 	at org.apache.tomcat.websocket.WsSession.checkState(WsSession.java:803)
2019-02-21T14:57:50.301125764Z 	at org.apache.tomcat.websocket.WsSession.getBasicRemote(WsSession.java:446)
2019-02-21T14:57:50.301149217Z 	at org.springframework.web.socket.adapter.standard.StandardWebSocketSession.sendTextMessage(StandardWebSocketSession.java:197)
2019-02-21T14:57:50.301172074Z 	at org.springframework.web.socket.adapter.AbstractWebSocketSession.sendMessage(AbstractWebSocketSession.java:104)
2019-02-21T14:57:50.301194724Z 	at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.sendRequestWebSocket(WebSocketServerSession.java:117)
2019-02-21T14:57:50.301217191Z 	... 22 common frames omitted
2019-02-21T14:57:50.301238747Z 

....

2019-02-21T14:58:19.267465468Z java.lang.NullPointerException: null
2019-02-21T14:58:19.267488854Z 	at io.openvidu.server.rpc.RpcHandler.handleUncaughtException(RpcHandler.java:616)
2019-02-21T14:58:19.267514098Z 	at org.kurento.jsonrpc.internal.JsonRpcHandlerManager.handleTransportError(JsonRpcHandlerManager.java:199)
2019-02-21T14:58:19.267538374Z 	at org.kurento.jsonrpc.internal.server.ProtocolManager.processTransportError(ProtocolManager.java:457)
2019-02-21T14:58:19.267561348Z 	at org.kurento.jsonrpc.internal.ws.JsonRpcWebSocketHandler.handleTransportError(JsonRpcWebSocketHandler.java:158)
2019-02-21T14:58:19.267583994Z 	at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleTransportError(WebSocketHandlerDecorator.java:80)
2019-02-21T14:58:19.267607068Z 	at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleTransportError(LoggingWebSocketHandlerDecorator.java:64)
2019-02-21T14:58:19.267630537Z 	at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.handleTransportError(ExceptionWebSocketHandlerDecorator.java:68)
2019-02-21T14:58:19.267653755Z 	at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.onError(StandardWebSocketHandlerAdapter.java:153)
2019-02-21T14:58:19.267676674Z 	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.onError(WsHttpUpgradeHandler.java:217)
2019-02-21T14:58:19.267699034Z 	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:152)
2019-02-21T14:58:19.267773760Z 	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
2019-02-21T14:58:19.267800397Z 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
2019-02-21T14:58:19.267823254Z 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
2019-02-21T14:58:19.267845820Z 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
2019-02-21T14:58:19.267868320Z 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
2019-02-21T14:58:19.267902453Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2019-02-21T14:58:19.267952833Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2019-02-21T14:58:19.267977737Z 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2019-02-21T14:58:19.268000699Z 	at java.lang.Thread.run(Thread.java:748)
2019-02-21T14:58:19.268022960Z 
2019-02-21T14:58:19.269043163Z 2019-02-21 14:58:19,267 DEBG 'openvidu-server' stdout output:
2019-02-21T14:58:19.269093363Z [INFO] 2019-02-21 14:58:19,266 [-8080-exec-9] org.apache.tomcat.websocket.server.WsRemoteEndpointImplServer (log) - Failed to close the ServletOutputStream connection cleanly
2019-02-21T14:58:19.269146320Z java.io.IOException: Broken pipe
2019-02-21T14:58:19.269171511Z 	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
2019-02-21T14:58:19.269194360Z 	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
2019-02-21T14:58:19.269216954Z 	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
2019-02-21T14:58:19.269239203Z 	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
2019-02-21T14:58:19.269261147Z 	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
2019-02-21T14:58:19.269314023Z 	at org.apache.tomcat.util.net.SecureNioChannel.flush(SecureNioChannel.java:143)
2019-02-21T14:58:19.269346760Z 	at org.apache.tomcat.util.net.SecureNioChannel.close(SecureNioChannel.java:508)
2019-02-21T14:58:19.269370053Z 	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.close(NioEndpoint.java:1165)
2019-02-21T14:58:19.269392520Z 	at org.apache.tomcat.websocket.server.WsRemoteEndpointImplServer.doClose(WsRemoteEndpointImplServer.java:171)
2019-02-21T14:58:19.269414996Z 	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.close(WsRemoteEndpointImplBase.java:710)
2019-02-21T14:58:19.269437130Z 	at org.apache.tomcat.websocket.WsSession.onClose(WsSession.java:532)
2019-02-21T14:58:19.269459210Z 	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.close(WsHttpUpgradeHandler.java:233)
2019-02-21T14:58:19.269481740Z 	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:155)
2019-02-21T14:58:19.269503985Z 	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
2019-02-21T14:58:19.269526490Z 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
2019-02-21T14:58:19.269548702Z 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
2019-02-21T14:58:19.269570926Z 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
2019-02-21T14:58:19.269593105Z 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
2019-02-21T14:58:19.269615350Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2019-02-21T14:58:19.269637432Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2019-02-21T14:58:19.269671363Z 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2019-02-21T14:58:19.269695382Z 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by oisnot** [comment]
Maybe I should post this at the Kurento github account?

**Comment by stianbakken** [comment]
https://github.com/OpenVidu/openvidu/issues/230
