### ISSUE TITLE
update 2.0.9 version and Get Error

### ISSUE THREAD

**Issue by kamlesh0606** [OpenVidu/openvidu#247]
Hi,

Following Error Came in console and Video not open

[ERROR] 2019-05-08 14:41:11,712 [tExec-e2-t10] org.kurento.client.internal.client.RemoteObjectInvocationHandler (propagateEventTo) - Exception while processing event 'IceComponentStateChangeEvent' with params '{componentId=1, streamId=1, source=3b6e3fed-44d8-4896-8eb6-425e33a1cc07_kurento.MediaPipeline/f74d82cc-6253-428c-9187-a58c6c415324_kurento.WebRtcEndpoint, state=READY, type=IceComponentStateChange, tags=[], timestamp=1557306671}'
**java.lang.NumberFormatException: null
	at java.lang.Long.parseLong(Long.java:552)
	at java.lang.Long.parseLong(Long.java:631)
	at io.openvidu.server.kurento.endpoint.KmsEvent.<init>(KmsEvent.java:39)
	at io.openvidu.server.kurento.core.KurentoParticipantEndpointConfig.lambda$addEndpointListeners$6(KurentoParticipantEndpointConfig.java:122)
	at org.kurento.client.internal.client.RemoteObjectInvocationHandler.propagateEventTo(RemoteObjectInvocationHandler.java:281)**
	at org.kurento.client.internal.client.RemoteObjectInvocationHandler$1.onEvent(RemoteObjectInvocationHandler.java:208)
	at org.kurento.client.internal.client.RemoteObject.fireEvent(RemoteObject.java:345)
	at org.kurento.client.internal.client.RomClientObjectManager.processEvent(RomClientObjectManager.java:58)
	at org.kurento.client.internal.transport.jsonrpc.RomClientJsonRpcClient.processEvent(RomClientJsonRpcClient.java:206)
	at org.kurento.client.internal.transport.jsonrpc.RomClientJsonRpcClient.access$000(RomClientJsonRpcClient.java:74)
	at org.kurento.client.internal.transport.jsonrpc.RomClientJsonRpcClient$1.handleRequest(RomClientJsonRpcClient.java:182)
	at org.kurento.jsonrpc.internal.JsonRpcHandlerManager.handleRequest(JsonRpcHandlerManager.java:128)
	at org.kurento.jsonrpc.client.AbstractJsonRpcClientWebSocket$15.run(AbstractJsonRpcClientWebSocket.java:577)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Thanks
kamlesh

**Comment by kamlesh0606** [comment]
Hi ,
Need to update Kurento 6.10.0 version But https://openvidu.io/docs/deployment/upgrading/ have old version.

Thanks
kamlesh
