### ISSUE TITLE
NullPointerException in publishVideo

### ISSUE THREAD

**Issue by steelden** [OpenVidu/openvidu#266]
Hello,

Server: OpenVidu 2.8.0.

We've just encountered a NullPointerException:
java.lang.NullPointerException: null
        at io.openvidu.server.kurento.core.KurentoSessionManager.publishVideo(KurentoSessionManager.java:285)
        at io.openvidu.server.rpc.RpcHandler.publishVideo(RpcHandler.java:262)
        at io.openvidu.server.rpc.RpcHandler.handleRequest(RpcHandler.java:118)
        at org.kurento.jsonrpc.internal.JsonRpcHandlerManager.handleRequest(JsonRpcHandlerManager.java:128)
        at org.kurento.jsonrpc.internal.server.ProtocolManager$3.run(ProtocolManager.java:218)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

[VideoServerLogs.20190611.194100.txt](https://github.com/OpenVidu/openvidu/files/3277648/VideoServerLogs.20190611.194100.txt)

Simple test conference for 2 people.

Are we missing some configuration?

**Comment by micaelgallego** [comment]
Please update to 2.10.0 version

**Comment by steelden** [comment]
Thanks, I'll give it a try.
