### ISSUE TITLE
Recording not starting in openvidu v2.8+

### ISSUE THREAD

**Issue by loveisalie92** [OpenVidu/openvidu#279]
Hi,

I'm trying to upgrade Openvidu from version 2.7.0 to higher version in able to use INDIVIDUAL recording mode.

But after the upgrade, the recording API does not works, it keeps returning the 500 error code (Java nullPointerExcetion). This is the message in terminal when i perform recording:

+ error waiting for some recorder endpoint to start in session ...
+ recording start failed for session ... couldn't initialize some RecorderEndpoint

There are files created in 'recordings' folder but with 0 bytes

I have tried with 3 version: 2.8.0, 2.9.0 and 2.10.0. the same error occurred for these 3 version.
Everything is working fine in 2.7.0

I'm using Ubuntu 16.04 for KMS/Openvidu server
Please help!

Thanks in advance

**Comment by micaelgallego** [comment]
Please test with latest version and details us what are the exact steps your are performing, what are the expected outcome and what is the buggy behavior you have.

Also, share with us the whole OpenVidu-server logs and KMS logs.

**Comment by Brianvdb** [comment]
Also getting errors for some of our users..
```
[INFO] 2019-06-26 11:49:33,021 [-5443-exec-5] io.openvidu.server.core.SessionManager (showTokens) - <SESSIONID, TOKENS>: {zgtecopgg5dwkur9={}, g8h3bl6qkznhjfvw={wss://partou-vidu.livewall.nl?sessionId=g8h3bl6qkznhjfvw&token=vvmfbgzd94ix4rty&role=PUBLISHER&version=2.10.0&turnUsername=PMRYOR&turnCredential=urj7q4=PUBLISHER}}
[INFO] 2019-06-26 11:49:33,030 [-5443-exec-6] io.openvidu.server.rest.SessionRestController (newToken) - REST API: POST /api/tokens {session=zgtecopgg5dwkur9}
[INFO] 2019-06-26 11:49:33,030 [-5443-exec-6] io.openvidu.server.coturn.CoturnCredentialsService (createUser) - Creating COTURN user
[INFO] 2019-06-26 11:49:33,045 [-5443-exec-6] io.openvidu.server.coturn.CoturnCredentialsService (createUser) - COTURN user created: true
[INFO] 2019-06-26 11:49:33,046 [-5443-exec-6] io.openvidu.server.core.SessionManager (showTokens) - <SESSIONID, TOKENS>: {zgtecopgg5dwkur9={wss://partou-vidu.livewall.nl?sessionId=zgtecopgg5dwkur9&token=jpczxqnd8hwm2gjx&role=PUBLISHER&version=2.10.0&turnUsername=YYUWLH&turnCredential=sk7f2g=PUBLISHER}, g8h3bl6qkznhjfvw={wss://partou-vidu.livewall.nl?sessionId=g8h3bl6qkznhjfvw&token=vvmfbgzd94ix4rty&role=PUBLISHER&version=2.10.0&turnUsername=PMRYOR&turnCredential=urj7q4=PUBLISHER}}
[INFO] 2019-06-26 11:49:33,270 [-5443-exec-8] io.openvidu.server.config.HttpHandshakeInterceptor (beforeHandshake) - New HttpSession 4758768EA6766D427AF79DF241C4E0C0
[INFO] 2019-06-26 11:49:33,302 [-5443-exec-9] io.openvidu.server.rpc.RpcHandler (afterConnectionEstablished) - After connection established for WebSocket session: dtqmq6i170igor33sq7vje63a7
[INFO] 2019-06-26 11:49:33,303 [e63a7-e37-t0] io.openvidu.server.core.SessionManager (newParticipant) - Participant 99fut1dyub9hbiyd of session zgtecopgg5dwkur9 belongs to a new final user
[WARN] 2019-06-26 11:49:33,304 [e63a7-e37-t0] io.openvidu.server.kurento.core.KurentoSessionManager (createSession) - No session 'zgtecopgg5dwkur9' exists yet. Created one using KurentoClient 'manager_ServerManager'.
[INFO] 2019-06-26 11:49:33,304 [e63a7-e37-t0] io.openvidu.server.core.Session (createPipeline) - SESSION zgtecopgg5dwkur9: Creating MediaPipeline
[INFO] 2019-06-26 11:49:33,310 [e63a7-e37-t0] io.openvidu.server.core.Session (join) - SESSION zgtecopgg5dwkur9: Added participant [participantPrivateId=dtqmq6i170igor33sq7vje63a7, participantPublicId=99fut1dyub9hbiyd, streaming=false]
[INFO] 2019-06-26 11:49:39,002 [e63a7-e37-t0] io.openvidu.server.rpc.RpcHandler (sanityCheckOfSession) - Participant 99fut1dyub9hbiyd is calling method 'publish' in session zgtecopgg5dwkur9
[INFO] 2019-06-26 11:49:39,019 [e63a7-e37-t0] io.openvidu.server.kurento.core.KurentoParticipant (publishToRoom) - PARTICIPANT 99fut1dyub9hbiyd: Request to publish video in room zgtecopgg5dwkur9 (sdp type OFFER)
[INFO] 2019-06-26 11:49:39,030 [e63a7-e37-t0] io.openvidu.server.kurento.core.KurentoParticipant (publishToRoom) - PARTICIPANT 99fut1dyub9hbiyd: Is now publishing video in room zgtecopgg5dwkur9
[INFO] 2019-06-26 11:49:39,031 [e63a7-e37-t0] io.openvidu.server.rpc.RpcHandler (sanityCheckOfSession) - Participant 99fut1dyub9hbiyd is calling method 'onIceCandidate' in session zgtecopgg5dwkur9
[INFO] 2019-06-26 11:49:39,032 [e63a7-e37-t0] io.openvidu.server.rpc.RpcHandler (sanityCheckOfSession) - Participant 99fut1dyub9hbiyd is calling method 'onIceCandidate' in session zgtecopgg5dwkur9
[INFO] 2019-06-26 11:49:39,032 [e63a7-e37-t0] io.openvidu.server.rpc.RpcHandler (sanityCheckOfSession) - Participant 99fut1dyub9hbiyd is calling method 'onIceCandidate' in session zgtecopgg5dwkur9
[INFO] 2019-06-26 11:49:39,033 [e63a7-e37-t0] io.openvidu.server.rpc.RpcHandler (sanityCheckOfSession) - Participant 99fut1dyub9hbiyd is calling method 'onIceCandidate' in session zgtecopgg5dwkur9
[INFO] 2019-06-26 11:49:39,099 [Exec-e2-t215] io.openvidu.server.kurento.core.KurentoParticipantEndpointConfig (lambda$addEndpointListeners$6) - KMS event [IceComponentStateChange]: -> endpoint: 99fut1dyub9hbiyd_CAMERA_OOTHT (publisher) | state: GATHERING | componentId: 1 | streamId: 1 | timestamp: 1561542579039
[INFO] 2019-06-26 11:49:39,100 [Exec-e2-t216] io.openvidu.server.kurento.core.KurentoParticipantEndpointConfig (lambda$addEndpointListeners$6) - KMS event [IceComponentStateChange]: -> endpoint: 99fut1dyub9hbiyd_CAMERA_OOTHT (publisher) | state: GATHERING | componentId: 2 | streamId: 1 | timestamp: 1561542579039
[INFO] 2019-06-26 11:49:39,100 [Exec-e2-t217] io.openvidu.server.kurento.core.KurentoParticipantEndpointConfig (lambda$addEndpointListeners$6) - KMS event [IceComponentStateChange]: -> endpoint: 99fut1dyub9hbiyd_CAMERA_OOTHT (publisher) | state: GATHERING | componentId: 1 | streamId: 2 | timestamp: 1561542579059
[INFO] 2019-06-26 11:49:39,101 [Exec-e2-t218] io.openvidu.server.kurento.core.KurentoParticipantEndpointConfig (lambda$addEndpointListeners$6) - KMS event [IceComponentStateChange]: -> endpoint: 99fut1dyub9hbiyd_CAMERA_OOTHT (publisher) | state: GATHERING | componentId: 2 | streamId: 2 | timestamp: 1561542579059
[INFO] 2019-06-26 11:49:39,101 [Exec-e2-t219] io.openvidu.server.kurento.core.KurentoParticipantEndpointConfig (lambda$addEndpointListeners$6) - KMS event [IceComponentStateChange]: -> endpoint: 99fut1dyub9hbiyd_CAMERA_OOTHT (publisher) | state: GATHERING | componentId: 1 | streamId: 3 | timestamp: 1561542579059
[INFO] 2019-06-26 11:49:39,102 [Exec-e2-t220] io.openvidu.server.kurento.core.KurentoParticipantEndpointConfig (lambda$addEndpointListeners$6) - KMS event [IceComponentStateChange]: -> endpoint: 99fut1dyub9hbiyd_CAMERA_OOTHT (publisher) | state: GATHERING | componentId: 2 | streamId: 3 | timestamp: 1561542579059
[INFO] 2019-06-26 11:49:39,102 [Exec-e2-t223] io.openvidu.server.kurento.core.KurentoParticipantEndpointConfig (lambda$addEndpointListeners$6) - KMS event [IceComponentStateChange]: -> endpoint: 99fut1dyub9hbiyd_CAMERA_OOTHT (publisher) | state: CONNECTING | componentId: 1 | streamId: 1 | timestamp: 1561542579062
[INFO] 2019-06-26 11:49:44,482 [-5443-exec-7] io.openvidu.server.rest.SessionRestController (startRecordingSession) - REST API: POST /api/recordings/start {session=zgtecopgg5dwkur9, outputMode=INDIVIDUAL}
[INFO] 2019-06-26 11:49:44,483 [-5443-exec-7] io.openvidu.server.recording.service.RecordingService (setFinalRecordingNameAndGetFreeRecordingId) - New recording id (zgtecopgg5dwkur9) and final name (zgtecopgg5dwkur9)
[INFO] 2019-06-26 11:49:44,483 [-5443-exec-7] io.openvidu.server.recording.service.SingleStreamRecordingService (startRecording) - Starting individual (video+audio) recording zgtecopgg5dwkur9 of session zgtecopgg5dwkur9
[INFO] 2019-06-26 11:49:44,483 [-5443-exec-7] io.openvidu.server.recording.service.SingleStreamRecordingService (startRecorderEndpointForPublisherEndpoint) - Starting single stream recorder for stream 99fut1dyub9hbiyd_CAMERA_OOTHT in session zgtecopgg5dwkur9
[ERROR] 2019-06-26 11:49:49,526 [-5443-exec-7] io.openvidu.server.recording.service.SingleStreamRecordingService (startRecording) - Error waiting for some recorder endpoint to start in session zgtecopgg5dwkur9
[ERROR] 2019-06-26 11:49:49,526 [-5443-exec-7] io.openvidu.server.recording.service.RecordingService (failStartRecording) - Recording start failed for session zgtecopgg5dwkur9: Couldn't initialize some RecorderEndpoint
```

Creating session
Joining session
When video and audio publishing > start recording.

Works fine overall but this error occurs for some of our users and I do not have more details..

**Comment by loveisalie92** [comment]
Hi, This is how i deploy the media server.

Deploy command:

java -jar -Dopenvidu.secret=123456 -Dopenvidu.recording=true -Dopenvidu.publicurl=https://192.168.1.71:4443 -Dopenvidu.recording.public-access=true -Dopenvidu.recording.path=/home/huynguyen/Desktop/recordings  openvidu-server-2.10.0.jar

In client client side (using openvidu browser js v2.10.0):
I can publish and subscribe stream normally, 2 clients can see each others. The error only occur when i call the api to start recording: api/recordings/start | Post

I don't think that i missing something in the API call because they are pretty simple.
Note: everything is working ok if i switch back to v2.7.0 for both client and media server

Here's the error log:

[INFO] 2019-06-27 09:13:02,671 [r19gnq-e4-t0] io.openvidu.server.rpc.RpcHandler (sanityCheckOfSession) - Participant iaor64u1o4u7dv67 is calling method 'signal' in session zrotmiam0hwhpgoa
[INFO] 2019-06-27 09:13:02,821 [-4443-exec-9] io.openvidu.server.rest.SessionRestController (startRecordingSession) - REST API: POST /api/recordings/start {session=zrotmiam0hwhpgoa}
[INFO] 2019-06-27 09:13:02,823 [-4443-exec-9] io.openvidu.server.recording.service.RecordingService (setFinalRecordingNameAndGetFreeRecordingId) - New recording id (zrotmiam0hwhpgoa) and final name (zrotmiam0hwhpgoa)
[INFO] 2019-06-27 09:13:02,824 [-4443-exec-9] io.openvidu.server.recording.service.SingleStreamRecordingService (startRecording) - Starting individual (video+audio) recording zrotmiam0hwhpgoa of session zrotmiam0hwhpgoa
[INFO] 2019-06-27 09:13:02,825 [-4443-exec-9] io.openvidu.server.recording.service.SingleStreamRecordingService (startRecorderEndpointForPublisherEndpoint) - Starting single stream recorder for stream awtddq1ihmkh6gln_CUSTOM_KKPKI in session zrotmiam0hwhpgoa
[ERROR] 2019-06-27 09:13:08,039 [-4443-exec-9] io.openvidu.server.recording.service.SingleStreamRecordingService (startRecording) - Error waiting for some recorder endpoint to start in session zrotmiam0hwhpgoa
[ERROR] 2019-06-27 09:13:08,040 [-4443-exec-9] io.openvidu.server.recording.service.RecordingService (failStartRecording) - Recording start failed for session zrotmiam0hwhpgoa: Couldn't initialize some RecorderEndpoint
[INFO] 2019-06-27 09:13:08,040 [-4443-exec-9] io.openvidu.server.recording.service.SingleStreamRecordingService (stopRecording) - Stopping individual (video+audio) recording zrotmiam0hwhpgoa of session zrotmiam0hwhpgoa. Reason: null
[INFO] 2019-06-27 09:13:08,040 [-4443-exec-9] io.openvidu.server.recording.service.SingleStreamRecordingService (stopRecorderEndpointOfPublisherEndpoint) - Stopping single stream recorder for stream awtddq1ihmkh6gln_CUSTOM_KKPKI in session zrotmiam0hwhpgoa
[ERROR] 2019-06-27 09:13:13,044 [-4443-exec-9] io.openvidu.server.recording.service.SingleStreamRecordingService (stopRecording) - Error waiting for some recorder endpoint to stop in session zrotmiam0hwhpgoa
[ERROR] 2019-06-27 09:13:13,049 [-4443-exec-9] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] (log) - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null
	at io.openvidu.server.recording.service.SingleStreamRecordingService.sealMetadataFiles(SingleStreamRecordingService.java:360)
	at io.openvidu.server.recording.service.SingleStreamRecordingService.stopRecording(SingleStreamRecordingService.java:161)
	at io.openvidu.server.recording.service.SingleStreamRecordingService.stopRecording(SingleStreamRecordingService.java:132)
	at io.openvidu.server.recording.service.RecordingService.failStartRecording(RecordingService.java:167)
	at io.openvidu.server.recording.service.SingleStreamRecordingService.startRecording(SingleStreamRecordingService.java:116)
	at io.openvidu.server.recording.service.RecordingManager.startRecording(RecordingManager.java:184)
	at io.openvidu.server.rest.SessionRestController.startRecordingSession(SessionRestController.java:497)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:220)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:169)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:215)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:121)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:89)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by pabloFuente** [comment]
Hi,

Make sure that your versions of all components are compatible with each other. If you are using OpenVidu 2.10.0, it is absolutely mandatory to comply with these version numbers: https://openvidu.io/docs/releases/#2100

So, the **openvidu-server JAR file** should be 2.10.0 and **KMS** should be 6.10.0. You can get its version with command `kurento-media-server --version`, that must return this output:

```
Kurento Media Server version: 6.10.0
Found modules:
	'core' version 6.10.0
	'elements' version 6.10.0
	'filters' version 6.10.0
```

And your **server client SDK** (openvidu-java-client, openvidu-node-client or REST API) must also be 2.10.0, as well as **openvidu-browser** client-side library. Just follow the table I linked above and comply wth those version numbers for each module.

**Comment by loveisalie92** [comment]
Hi @pabloFuente,

Thanks for your help,
After install all compatible components, I have found the reason why i get that error,

That's because i'm missing {hasAudio: false} in my api call, as the publisher only publish video and i 'm guessing that The media server try to record both audio and video so it failed. This also explain why @Brianvdb has this issue sometime for his users (maybe they not fully allow the browser to publish both video and audio or the they just use webcam without a mic)

Thank again guys :)

**Comment by nitin-** [comment]
> Hi,
> 
> I'm trying to upgrade Openvidu from version 2.7.0 to higher version in able to use INDIVIDUAL recording mode.
> 
> But after the upgrade, the recording API does not works, it keeps returning the 500 error code (Java nullPointerExcetion). This is the message in terminal when i perform recording:
> 
> * error waiting for some recorder endpoint to start in session ...
> * recording start failed for session ... couldn't initialize some RecorderEndpoint
> 
> There are files created in 'recordings' folder but with 0 bytes
> 
> I have tried with 3 version: 2.8.0, 2.9.0 and 2.10.0. the same error occurred for these 3 version.
> Everything is working fine in 2.7.0
> 
> I'm using Ubuntu 16.04 for KMS/Openvidu server
> Please help!
> 
> Thanks in advance

I am trying to record Audio only using 2.7.0 , One of my participant is not publishing its video but Its nor working 

Before adding the recording API call everything was working fine.

**Comment by pabloFuente** [comment]
Hi,

OpenVidu 2.7.0 was release 2 and a half years ago. Many thins have changed and improved over this time, and the best part is that there has been almost no breaking changes in OpenVidu APIs. If you update to the latest release chances are you won't really have to make lots of changes.
