### ISSUE TITLE
Openvidu recording using windows docker

### ISSUE THREAD

**Issue by L-BuenoSRP** [OpenVidu/openvidu#298]
Hi, i have installed openvidu with docker for windows. I tried hello-world demo and everything is working fine.
But i try recording (only add , recordingMode: "ALWAYS" in app.js)and change docker parameters like the tutorials said and is not working.

First of all, from the documentation:

IMPORTANT! /PATH/TO/VIDEO/FILES must be the same in property openvidu.recording.path=/PATH/TO/VIDEO/FILES and in both sides of flag -v /PATH/TO/VIDEO/FILES:/PATH/TO/VIDEO/FILES

Docker for Windows needs to be executed with the drive letter for share folders so i need to use something like that(look at c: before /openvidu):

docker run -p 4443:4443 --rm -v /var/run/docker.sock:/var/run/docker.sock \
-v c:/openvidu/recordings:/opt/openvidu/recordings -v c:/openvidu/cert:/opt/openvidu/cert \
-e openvidu.recording=true -e openvidu.recording.path=/opt/openvidu/recordings \
-e openvidu.publicurl=https://edtsi139:4443/ -e openvidu.recording=true \
-e server.ssl.key-store=/opt/openvidu/cert/edtsi139.jks \
-e server.ssl.key-store-password="Telemedicina" \
-e server.ssl.key-alias="EDTSI139" openvidu/openvidu-server-kms:2.10.0

So both sides of flag are different.

If I run this command I get this error when trying to save the record.

There was an error generating the metadata report file for the recording. Code: 702
        at io.openvidu.server.recording.service.ComposedRecordingService.stopRecordingWithVideo(ComposedRecordingService.java:324)
        at io.openvidu.server.recording.service.ComposedRecordingService.stopRecording(ComposedRecordingService.java:102)
        at io.openvidu.server.recording.service.ComposedRecordingService.stopRecording(ComposedRecordingService.java:96)
        at io.openvidu.server.recording.service.RecordingManager.stopRecording(RecordingManager.java:209)
        at io.openvidu.server.rest.SessionRestController.stopRecordingSession(SessionRestController.java:527)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:220)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)

I also tried to map as c: / openvidu: / opt / openvidu to get the write root path and ssl certificate

What else needs to be done to map the local directory for the use of recording and reading certificates?
Thanks

**Comment by pabloFuente** [comment]
Please, use Google Mailing List (https://groups.google.com/forum/m/#!forum/openvidu) to get this kind of support. This is not an issue, this is a matter of configuring the development environment with the proper values.
