### ISSUE TITLE
Recording Not working in Always mode. If session has triggred stopped recording and session is simultaenously started then the new session is not getting recorded.

### ISSUE THREAD

**Issue by abhi021** [OpenVidu/openvidu#364]
[INFO] 2019-11-26 05:32:45,422 [l-1-thread-8] io.openvidu.server.recording.service.RecordingManager (lambda$initAutomaticRecordingStopThread$2) - Stopping recording 3a94ea17-692d-4337-a8a5-9f8f9dfabc7e after 120 seconds wait (no publisher published before timeout)
[INFO] 2019-11-26 05:32:45,422 [l-1-thread-8] io.openvidu.server.recording.service.ComposedRecordingService (stopRecordingWithVideo) - Stopping composed (video + audio) recording 3a94ea17-692d-4337-a8a5-9f8f9dfabc7e of session 3a94ea17-692d-4337-a8a5-9f8f9dfabc7e. Reason: automaticStop
[ERROR] 2019-11-26 05:32:46,312 [-4443-exec-7] io.openvidu.server.rpc.RpcHandler (handleTransportError) - Transport exception for WebSocket session: 3eedmnc8fm4o85ovdmf20upe44 - Exception: null
[INFO] 2019-11-26 05:32:46,607 [l-1-thread-8] io.openvidu.server.cdr.CDRLoggerFile (log) - {"recordingStopped":{"sessionId":"3a94ea17-692d-4337-a8a5-9f8f9dfabc7e","timestamp":1574746366607,"startTime":1574745620727,"duration":742.234,"reason":"automaticStop","id":"3a94ea17-692d-4337-a8a5-9f8f9dfabc7e","name":"3a94ea17-692d-4337-a8a5-9f8f9dfabc7e","outputMode":"COMPOSED","resolution":"1920x1080","recordingLayout":"BEST_FIT","hasAudio":true,"hasVideo":true,"size":35922404}}
[INFO] 2019-11-26 05:32:47,414 [-4443-exec-1] io.openvidu.server.rest.SessionRestController (getSessionId) - REST API: POST /api/sessions {customSessionId=3a94ea17-692d-4337-a8a5-9f8f9dfabc7e, recordingMode=ALWAYS}
[INFO] 2019-11-26 05:32:47,440 [-4443-exec-3] io.openvidu.server.rest.SessionRestController (newToken) - REST API: POST /api/tokens {session=3a94ea17-692d-4337-a8a5-9f8f9dfabc7e, role=SUBSCRIBER}
[INFO] 2019-11-26 05:32:47,441 [-4443-exec-3] io.openvidu.server.core.SessionManager (showTokens) - <SESSIONID, TOKENS>: {3a94ea17-692d-4337-a8a5-9f8f9dfabc7e={wss://refierservices.refier.com?sessionId=3a94ea17-692d-4337-a8a5-9f8f9dfabc7e&token=a4yakp5v7idgzqdv&role=SUBSCRIBER&version=2.10.0=SUBSCRIBER}}
[INFO] 2019-11-26 05:32:47,509 [-4443-exec-8] io.openvidu.server.config.HttpHandshakeInterceptor (beforeHandshake) - Old HttpSession 54D719B9410042693E8DEA53641BE32D
[INFO] 2019-11-26 05:32:47,539 [4443-exec-10] io.openvidu.server.rpc.RpcHandler (afterConnectionEstablished) - After connection established for WebSocket session: 3d0atpmhf6i6460pmrv613c2fb
[INFO] 2019-11-26 05:32:47,541 [3c2fb-e59-t0] io.openvidu.server.rpc.RpcHandler (joinRoom) - Final user reconnecting
[INFO] 2019-11-26 05:32:47,541 [3c2fb-e59-t0] io.openvidu.server.core.SessionManager (newParticipant) - Participant oxprdqacciyansan of session 3a94ea17-692d-4337-a8a5-9f8f9dfabc7e belongs to a previously existing user

I cannot see the line "PARTICIPANT RECORDER: Request to receive media from 7irmvay5rwli1eui in room 3a94ea17-692d-4337-a8a5-9f8f9dfabc7e" 

Thanks

**Comment by abhi021** [comment]
Also received the following error in log 

[ERROR] 2019-11-26 05:32:47,543 [3c2fb-e59-t0] io.openvidu.server.rpc.RpcNotificationService (sendNotification) - Exception sending notification 'participantJoined': {"id":"oxprdqacciyansan","createdAt":1574746367541,"metadata":"{\"clientData\":\"Abhishek Kumar\",\"clientUserId\":\"bf21ce98-4734-416a-ac94-536a93dae6e9\"}"} to participant with private id 3eedmnc8fm4o85ovdmf20upe44
org.kurento.commons.exception.KurentoException: Exception while sending message '{"method":"participantJoined","params":{"id":"oxprdqacciyansan","createdAt":1574746367541,"metadata":"{\"clientData\":\"Abhishek Kumar\",\"clientUserId\":\"bf21ce98-4734-416a-ac94-536a93dae6e9\"}"},"jsonrpc":"2.0"}' to websocket with native sessionId '3c'
        at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.sendRequestWebSocket(WebSocketServerSession.java:121)
        at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.access$000(WebSocketServerSession.java:48)
        at org.kurento.jsonrpc.internal.ws.WebSocketServerSession$1.internalSendRequest(WebSocketServerSession.java:72)
        at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendRequest(JsonRpcRequestSenderHelper.java:75)
        at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendNotification(JsonRpcRequestSenderHelper.java:156)
        at org.kurento.jsonrpc.internal.server.ServerSession.sendNotification(ServerSession.java:121)
        at io.openvidu.server.rpc.RpcNotificationService.sendNotification(RpcNotificationService.java:98)
        at io.openvidu.server.core.SessionEventsHandler.onParticipantJoined(SessionEventsHandler.java:151)
        at io.openvidu.server.kurento.core.KurentoSessionManager.joinRoom(KurentoSessionManager.java:121)
        at io.openvidu.server.rpc.RpcHandler.joinRoom(RpcHandler.java:259)
        at io.openvidu.server.rpc.RpcHandler.handleRequest(RpcHandler.java:117)
        at org.kurento.jsonrpc.internal.JsonRpcHandlerManager.handleRequest(JsonRpcHandlerManager.java:128)
        at org.kurento.jsonrpc.internal.server.ProtocolManager$3.run(ProtocolManager.java:218)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: The WebSocket session [3c] has been closed and no method (apart from close()) may be called on a closed session
        at org.apache.tomcat.websocket.WsSession.checkState(WsSession.java:803)
        at org.apache.tomcat.websocket.WsSession.getBasicRemote(WsSession.java:446)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketSession.sendTextMessage(StandardWebSocketSession.java:197)
        at org.springframework.web.socket.adapter.AbstractWebSocketSession.sendMessage(AbstractWebSocketSession.java:104)
        at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.sendRequestWebSocket(WebSocketServerSession.java:117)
        ... 15 common frames omitted
[INFO] 2019-11-26 05:32:47,589 [3c2fb-e59-t0] io.openvidu.server.rpc.RpcHandler (sanityCheckOfSession) - Participant oxprdqacciyansan is calling method 'signal' in session 3a94ea17-692d-4337-a8a5-9f8f9dfabc7e
[ERROR] 2019-11-26 05:32:47,590 [3c2fb-e59-t0] io.openvidu.server.rpc.RpcNotificationService (sendNotification) - Exception sending notification 'sendMessage': {"data":"{\"isScreenShareActive\":false}","from":"oxprdqacciyansan","type":"signal:userChanged"} to participant with private id 3eedmnc8fm4o85ovdmf20upe44
org.kurento.commons.exception.KurentoException: Exception while sending message '{"method":"sendMessage","params":{"data":"{\"isScreenShareActive\":false}","from":"oxprdqacciyansan","type":"signal:userChanged"},"jsonrpc":"2.0"}' to websocket with native sessionId '3c'
        at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.sendRequestWebSocket(WebSocketServerSession.java:121)
        at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.access$000(WebSocketServerSession.java:48)
        at org.kurento.jsonrpc.internal.ws.WebSocketServerSession$1.internalSendRequest(WebSocketServerSession.java:72)
        at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendRequest(JsonRpcRequestSenderHelper.java:75)
        at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendNotification(JsonRpcRequestSenderHelper.java:156)
        at org.kurento.jsonrpc.internal.server.ServerSession.sendNotification(ServerSession.java:121)
        at io.openvidu.server.rpc.RpcNotificationService.sendNotification(RpcNotificationService.java:98)
        at io.openvidu.server.core.SessionEventsHandler.onSendMessage(SessionEventsHandler.java:341)
        at io.openvidu.server.kurento.core.KurentoSessionManager.sendMessage(KurentoSessionManager.java:435)
        at io.openvidu.server.rpc.RpcHandler.sendMessage(RpcHandler.java:356)
        at io.openvidu.server.rpc.RpcHandler.handleRequest(RpcHandler.java:135)
        at org.kurento.jsonrpc.internal.JsonRpcHandlerManager.handleRequest(JsonRpcHandlerManager.java:128)
        at org.kurento.jsonrpc.internal.server.ProtocolManager$3.run(ProtocolManager.java:218)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: The WebSocket session [3c] has been closed and no method (apart from close()) may be called on a closed session

**Comment by abhi021** [comment]
@micaelgallego please review this

**Comment by micaelgallego** [comment]
Can you detail how to reproduce the error please?

**Comment by abhi021** [comment]
1. Start a session with recording on.
2. Close the session, recording quits after 2 minute(or whatever is the set time period)
3. Start  the session again, just after quit recording is send and  before recording docker container is killed.
Error occurs because docker container for recording is already up(which is about to die ).

**Comment by micaelgallego** [comment]
Hi @abhi021, 

Thank you for reporting. We will take a look to this issue soon.

Look @pabloFuente

**Comment by pabloFuente** [comment]
Hi,

I've been able to replicate the issue. Well, I'm not 100% sure it is the same issue, but it is an issue nonetheless. I followd these steps:

1) Initialize a Session **forcing a session identifier with `customSessionId` parameter of POST /api/sessions**
2) Join a single user to the session and publish a video stream
3) Start composed video recording (a docker recording container will be launched)
4) Remove the single user from the session. OpenVidu will try to close and remove the session, but as it is actively being recorded, a timeout of 2 minutes by defult will start before automatically ending both the recording and the session. This is all explained here: https://openvidu.io/docs/advanced-features/recording/#automatic-stop-of-recordings
5) Just when the timout ellapses and the process of stopping the recording container and closing the session has started (and before it completes), create a new session *with the same customSessionId* as before and join a user to it.
Here comes the problem: the user joins and publsihes successfully to the session, but after the recording container has stopped, the same process closes the session. So the user is forcely evicted from the session without any apparent reason.

So, this issue (which I'm not sure is the same you described) is clearly a concurrency problem for this very specific case when using the same customSessionId. We'll try to fix for the next release.

Regards

**Comment by pabloFuente** [comment]
Commit 46d6199d427298ea0f1b6c64d055771f0bbb0da9 in master branch should fix this issue.

A ReadWriteLock protection has been added to all the Session closing operations scattered throughout openvidu-server code. The following "read" operations are now protected while a Session is in the process of closing (which is the operation that acquires write protection), stopping its recording included:

- Creating new Tokens for the session (REST operation `POST /api/tokens`)
- Joining users to a session with already created tokens (client RPC operation [Session.connect](https://openvidu.io/api/openvidu-browser/classes/session.html#connect))
- Publishing IP cameras (REST operation `POST /api/sessions/<SESSION_ID>/connection`, currently in the master dev branch and officially available in next release).

So none of them will success if the close up of a session is going on at that moment. Read lock acquirement is done with `tryLock` instead of `lock`, so all 3 operations will return immediately throwing a rather explanatory error, instead of explicitely waiting for the write operation to finish (which wouldn't make sense, as they would encounter a closed session when trying to fulfill their internal procedures after the session's close up opeation unlocks the WriteLock).
