### ISSUE TITLE
Broken pipe when a call to the endpoint to stop recording is made

### ISSUE THREAD

**Issue by jcancig** [OpenVidu/openvidu#368]
When I make a call to the rest endpoint to stop a recording I always get the same error, although the recording is done correctly and does not interfere with the operation of the rest of the video conferences or the videoconference being recorded.

It is an installation done on an Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-72-generic x86_64) following the instructions in the documentation.

This is the error: 

_[INFO] 2019-12-18 20:08:18,155 [0.0-4443-exec-5] io.openvidu.server.rest.SessionRestController (stopRecordingSession) - REST API: POST /api/recordings/stop/5df7669aa63da4.25496922
[INFO] 2019-12-18 20:08:18,216 [0.0-4443-exec-5] io.openvidu.server.webhook.HttpWebhookSender (sendHttpPostCallback) - Event recordingStatusChanged successfully posted to uri https://quantum.io/openvidu/webhook
[INFO] 2019-12-18 20:08:18,218 [0.0-4443-exec-5] io.openvidu.server.recording.service.RecordingService (sealRecordingMetadataFile) - Sealed recording metadata file at /home/quantum/web/quantum.io/public_html/storage/app/tmp/5df7669aa63da4.25496922/.recording.5df7669aa63da4.25496922 with status [stopped]
[INFO] 2019-12-18 20:08:18,218 [0.0-4443-exec-5] io.openvidu.server.recording.service.ComposedRecordingService (stopRecordingWithVideo) - Stopping composed (video + audio) recording 5df7669aa63da4.25496922 of session 5df7669aa63da4.25496922. Reason: recordingStoppedByServer
[ERROR] 2019-12-18 20:08:19,610 [0.0-4443-exec-7] io.openvidu.server.rpc.RpcHandler (handleTransportError) - Transport exception for WebSocket session: mmvsgh836k21ccnl4h601rfvik - Exception: null
[INFO] 2019-12-18 20:08:19,646 [0.0-4443-exec-7] org.apache.tomcat.websocket.server.WsRemoteEndpointImplServer (log) - Failed to close the ServletOutputStream connection cleanly
java.io.IOException: Broken pipe
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:65)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
        at org.apache.tomcat.util.net.SecureNioChannel.flush(SecureNioChannel.java:144)
        at org.apache.tomcat.util.net.SecureNioChannel.close(SecureNioChannel.java:524)
        at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.close(NioEndpoint.java:1208)
        at org.apache.tomcat.websocket.server.WsRemoteEndpointImplServer.doClose(WsRemoteEndpointImplServer.java:222)
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.close(WsRemoteEndpointImplBase.java:710)
        at org.apache.tomcat.websocket.WsSession.onClose(WsSession.java:538)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.close(WsHttpUpgradeHandler.java:232)
        at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:155)
        at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1747)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
[INFO] 2019-12-18 20:08:19,992 [0.0-4443-exec-5] io.openvidu.server.recording.service.RecordingService (sealRecordingMetadataFile) - Sealed recording metadata file at /home/quantum/web/quantum.io/public_html/storage/app/tmp/5df7669aa63da4.25496922/.recording.5df7669aa63da4.25496922 with status [ready]
[INFO] 2019-12-18 20:08:20,095 [0.0-4443-exec-5] io.openvidu.server.webhook.HttpWebhookSender (sendHttpPostCallback) - Event recordingStatusChanged successfully posted to uri https://quantum.io/openvidu/webhook
[INFO] 2019-12-18 20:08:20,097 [0.0-4443-exec-5] io.openvidu.server.core.Session (leave) - PARTICIPANT RECORDER: Leaving session 5df7669aa63da4.25496922
[INFO] 2019-12-18 20:08:20,097 [0.0-4443-exec-5] io.openvidu.server.kurento.core.KurentoParticipant (cancelReceivingMedia) - PARTICIPANT gbtdq9b2ppnedl7i: cancel receiving media from RECORDER
[WARN] 2019-12-18 20:08:20,098 [0.0-4443-exec-5] io.openvidu.server.kurento.core.KurentoParticipant (cancelReceivingMedia) - PARTICIPANT gbtdq9b2ppnedl7i: Trying to cancel receiving video from user RECORDER. But there is no such subscriber endpoint.
[INFO] 2019-12-18 20:08:20,098 [0.0-4443-exec-5] io.openvidu.server.kurento.core.KurentoParticipant (cancelReceivingMedia) - PARTICIPANT d2xiwhhgwxqpnicf: cancel receiving media from RECORDER
[WARN] 2019-12-18 20:08:20,098 [0.0-4443-exec-5] io.openvidu.server.kurento.core.KurentoParticipant (cancelReceivingMedia) - PARTICIPANT d2xiwhhgwxqpnicf: Trying to cancel receiving video from user RECORDER. But there is no such subscriber endpoint.
[WARN] 2019-12-18 20:08:20,101 [0.0-4443-exec-5] io.openvidu.server.kurento.core.KurentoParticipant (releasePublisherEndpoint) - PARTICIPANT RECORDER: Trying to release publisher endpoint but is null_

**Comment by pabloFuente** [comment]
Yeah, don't worry about that error.
This happens because the recording container does not exit the session as a regular user. OpenVidu simply destroys the container, and that may trigger a message warning about some user not being able to receive the expected "session left" message. We should probably filter this specific error listener to avoid printing it if it comes from a recording user.
