### ISSUE TITLE
Missing closed individual recording

### ISSUE THREAD

**Issue by EdiMel** [OpenVidu/openvidu#411]
**Describe the bug**
One recording do not got zipped correctly in the recordings folder

**Expected behavior**
All finished recordings should be zipped as described in the [docs](https://openvidu.io/docs/advanced-features/recording/#individual-stream-recording)

**Wrong current behavior**
The logs shows this for the recording:
`[ERROR] 2020-03-09 13:12:35,056 [0.0-5443-exec-3] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] (log) - Servlet.service() for servlet [dispatcherServlet] 
in context with path [] threw exception [Request processing failed; nested exception is com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLe
nient(true) to accept malformed JSON at line 1 column 283 path $] with root cause
com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 283 path $
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
        at com.google.gson.Gson.assertFullConsumption(Gson.java:899)
        at com.google.gson.Gson.fromJson(Gson.java:866)
        at io.openvidu.server.recording.service.SingleStreamRecordingService.sealMetadataFiles(SingleStreamRecordingService.java:415)
        at io.openvidu.server.recording.service.SingleStreamRecordingService.lambda$stopRecording$0(SingleStreamRecordingService.java:177)
        at io.openvidu.server.recording.DummyRecordingDownloader.downloadRecording(DummyRecordingDownloader.java:12)
        at io.openvidu.server.recording.service.SingleStreamRecordingService.stopRecording(SingleStreamRecordingService.java:170)
        at io.openvidu.server.recording.service.SingleStreamRecordingService.stopRecording(SingleStreamRecordingService.java:138)
        at io.openvidu.server.recording.service.RecordingManager.stopRecording(RecordingManager.java:227)
        at io.openvidu.server.core.SessionManager.closeSessionAndEmptyCollections(SessionManager.java:479)
        at io.openvidu.server.core.SessionManager.closeSession(SessionManager.java:469)
        at io.openvidu.server.rest.SessionRestController.closeSession(SessionRestController.java:217)
        at sun.reflect.GeneratedMethodAccessor60.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)`

**OpenVidu deployment info**
- 2.11 AWS deployment as explained in OpenVidu Docs (https://openvidu.io/docs/deployment/deploying-aws/)

**Comment by pabloFuente** [comment]
When does this happen? Everytime you try to stop an individual recording? Just some times? Depends on the nature of the streams being recorded? (audio, video, audio+video, browser emitting the media....). We need some way of replicating the error. Can you provide to us further information?
Could you please also try with OpenVidu 2.12.0 to see if the problem persists in the new release?

Thank you.

**Comment by pabloFuente** [comment]
This problem was fixed in 2.15.0. The related issue was this one: https://github.com/OpenVidu/openvidu/issues/479
