### ISSUE TITLE
Timeout error.. restart needed

### ISSUE THREAD

**Issue by EdiMel** [OpenVidu/openvidu#445]
**Describe the bug**
Video stop appearing in the browser after see a timeout error on supervisor.d  Include full error at the end.

```
Caused by: java.util.concurrent.TimeoutException: null
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:411)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:84)
        at org.kurento.jsonrpc.client.AbstractJsonRpcClientWebSocket.internalSendRequestWebSocket(AbstractJsonRpcClientWebSocket.java:377)
        ... 21 common frames omitted

```

**Expected behavior**
This error should not happen

**Wrong current behavior**
Cannot start video on browser after that.. restart on kurento needed

**OpenVidu tutorial where to replicate the error**
Cannot replicate, happened in production enviroment... I had full logs if you need something else

**OpenVidu deployment info**
- AWS deployment as explained in OpenVidu Docs (https://docs.openvidu.io/en/stable/deployment/deploying-aws/) Version 2.11

**Additional context**
Here goes the full error:
```
[ERROR] 2020-04-23 15:12:28,476 [hasrnm-e2116-t0] org.kurento.jsonrpc.internal.JsonRpcHandlerManager (handleRequest) - Exception while processing request {"id":9,"method":"publishVideo","params":{"sdpOffer":"v=0\r\no=- 4414433527680099703 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1\r\na=msid-semantic: WMS QDw7PUKTkQnrT75N8P86dNdvPKaFCrdyRdvI\r\nm=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:+Q6K\r\na=ice-pwd:QS0HZQUhFg7v0A87zaVB6v0v\r\na=ice-options:trickle\r\na=fingerprint:sha-256 F7:46:E9:C8:47:56:26:CC:1C:FA:46:A4:DA:29:C0:D5:5E:96:DB:9E:EC:40:3E:30:07:D2:AB:8E:05:74:8D:24\r\na=setup:actpass\r\na=mid:0\r\na=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendonly\r\na=msid:QDw7PUKTkQnrT75N8P86dNdvPKaFCrdyRdvI 82c9906b-b1a3-4a2e-a7ac-49f4a9d59939\r\na=rtcp-mux\r\na=rtpmap:111 opus/48000/2\r\na=rtcp-fb:111 transport-cc\r\na=fmtp:111 minptime=10;useinbandfec=1\r\na=rtpmap:103 ISAC/16000\r\na=rtpmap:104 ISAC/32000\r\na=rtpmap:9 G722/8000\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:106 CN/32000\r\na=rtpmap:105 CN/16000\r\na=rtpmap:13 CN/8000\r\na=rtpmap:110 telephone-event/48000\r\na=rtpmap:112 telephone-event/32000\r\na=rtpmap:113 telephone-event/16000\r\na=rtpmap:126 telephone-event/8000\r\na=ssrc:3828860366 cname:Q0XU66g2aUDwZehK\r\na=ssrc:3828860366 msid:QDw7PUKTkQnrT75N8P86dNdvPKaFCrdyRdvI 82c9906b-b1a3-4a2e-a7ac-49f4a9d59939\r\na=ssrc:3828860366 mslabel:QDw7PUKTkQnrT75N8P86dNdvPKaFCrdyRdvI\r\na=ssrc:3828860366 label:82c9906b-b1a3-4a2e-a7ac-49f4a9d59939\r\nm=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 122 127 121 125 107 108 109 124 120 123\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:+Q6K\r\na=ice-pwd:QS0HZQUhFg7v0A87zaVB6v0v\r\na=ice-options:trickle\r\na=fingerprint:sha-256 F7:46:E9:C8:47:56:26:CC:1C:FA:46:A4:DA:29:C0:D5:5E:96:DB:9E:EC:40:3E:30:07:D2:AB:8E:05:74:8D:24\r\na=setup:actpass\r\na=mid:1\r\na=extmap:14 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:13 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:12 urn:3gpp:video-orientation\r\na=extmap:2 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:6 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type\r\na=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing\r\na=extmap:8 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07\r\na=extmap:9 http://www.webrtc.org/experiments/rtp-hdrext/color-space\r\na=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:4 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id\r\na=extmap:5 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id\r\na=sendonly\r\na=msid:QDw7PUKTkQnrT75N8P86dNdvPKaFCrdyRdvI ec7d5988-bb7c-4851-983e-9e472a4dc1ef\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:96 VP8/90000\r\na=rtcp-fb:96 goog-remb\r\na=rtcp-fb:96 transport-cc\r\na=rtcp-fb:96 ccm fir\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 nack pli\r\na=rtpmap:97 rtx/90000\r\na=fmtp:97 apt=96\r\na=rtpmap:98 VP9/90000\r\na=rtcp-fb:98 goog-remb\r\na=rtcp-fb:98 transport-cc\r\na=rtcp-fb:98 ccm fir\r\na=rtcp-fb:98 nack\r\na=rtcp-fb:98 nack pli\r\na=fmtp:98 profile-id=0\r\na=rtpmap:99 rtx/90000\r\na=fmtp:99 apt=98\r\na=rtpmap:100 VP9/90000\r\na=rtcp-fb:100 goog-remb\r\na=rtcp-fb:100 transport-cc\r\na=rtcp-fb:100 ccm fir\r\na=rtcp-fb:100 nack\r\na=rtcp-fb:100 nack pli\r\na=fmtp:100 profile-id=2\r\na=rtpmap:101 rtx/90000\r\na=fmtp:101 apt=100\r\na=rtpmap:102 H264/90000\r\na=rtcp-fb:102 goog-remb\r\na=rtcp-fb:102 transport-cc\r\na=rtcp-fb:102 ccm fir\r\na=rtcp-fb:102 nack\r\na=rtcp-fb:102 nack pli\r\na=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f\r\na=rtpmap:122 rtx/90000\r\na=fmtp:122 apt=102\r\na=rtpmap:127 H264/90000\r\na=rtcp-fb:127 goog-remb\r\na=rtcp-fb:127 transport-cc\r\na=rtcp-fb:127 ccm fir\r\na=rtcp-fb:127 nack\r\na=rtcp-fb:127 nack pli\r\na=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f\r\na=rtpmap:121 rtx/90000\r\na=fmtp:121 apt=127\r\na=rtpmap:125 H264/90000\r\na=rtcp-fb:125 goog-remb\r\na=rtcp-fb:125 transport-cc\r\na=rtcp-fb:125 ccm fir\r\na=rtcp-fb:125 nack\r\na=rtcp-fb:125 nack pli\r\na=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=rtpmap:107 rtx/90000\r\na=fmtp:107 apt=125\r\na=rtpmap:108 H264/90000\r\na=rtcp-fb:108 goog-remb\r\na=rtcp-fb:108 transport-cc\r\na=rtcp-fb:108 ccm fir\r\na=rtcp-fb:108 nack\r\na=rtcp-fb:108 nack pli\r\na=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f\r\na=rtpmap:109 rtx/90000\r\na=fmtp:109 apt=108\r\na=rtpmap:124 red/90000\r\na=rtpmap:120 rtx/90000\r\na=fmtp:120 apt=124\r\na=rtpmap:123 ulpfec/90000\r\na=ssrc-group:FID 3113251707 1315689056\r\na=ssrc:3113251707 cname:Q0XU66g2aUDwZehK\r\na=ssrc:3113251707 msid:QDw7PUKTkQnrT75N8P86dNdvPKaFCrdyRdvI ec7d5988-bb7c-4851-983e-9e472a4dc1ef\r\na=ssrc:3113251707 mslabel:QDw7PUKTkQnrT75N8P86dNdvPKaFCrdyRdvI\r\na=ssrc:3113251707 label:ec7d5988-bb7c-4851-983e-9e472a4dc1ef\r\na=ssrc:1315689056 cname:Q0XU66g2aUDwZehK\r\na=ssrc:1315689056 msid:QDw7PUKTkQnrT75N8P86dNdvPKaFCrdyRdvI ec7d5988-bb7c-4851-983e-9e472a4dc1ef\r\na=ssrc:1315689056 mslabel:QDw7PUKTkQnrT75N8P86dNdvPKaFCrdyRdvI\r\na=ssrc:1315689056 label:ec7d5988-bb7c-4851-983e-9e472a4dc1ef\r\n","doLoopback":false,"hasAudio":true,"hasVideo":true,"audioActive":true,"videoActive":true,"typeOfVideo":"CAMERA","frameRate":30,"videoDimensions":"{\"width\":640,\"height\":480}"},"jsonrpc":"2.0"}
org.kurento.jsonrpc.JsonRpcException: [KurentoClient]  Timeout of 10000 milliseconds waiting from response to request {"id":79961,"method":"create","params":{"type":"PassThrough","constructorParams":{"mediaPipeline":"87449d1c-a559-4933-9bb4-5a42b9998a1e_kurento.MediaPipeline"},"properties":{},"sessionId":"eae133c8-8f9c-402c-82f3-0f0657c3521c"},"jsonrpc":"2.0"}
        at org.kurento.jsonrpc.client.AbstractJsonRpcClientWebSocket.internalSendRequestWebSocket(AbstractJsonRpcClientWebSocket.java:399)
        at org.kurento.jsonrpc.client.AbstractJsonRpcClientWebSocket$1.internalSendRequest(AbstractJsonRpcClientWebSocket.java:141)
        at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendRequest(JsonRpcRequestSenderHelper.java:75)
        at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendRequest(JsonRpcRequestSenderHelper.java:69)
        at org.kurento.jsonrpc.client.JsonRpcClient.sendRequest(JsonRpcClient.java:112)
        at org.kurento.client.internal.transport.jsonrpc.RomClientJsonRpcClient.sendRequest(RomClientJsonRpcClient.java:228)
        at org.kurento.client.internal.transport.jsonrpc.RomClientJsonRpcClient.create(RomClientJsonRpcClient.java:157)
        at org.kurento.client.internal.transport.jsonrpc.RomClientJsonRpcClient.create(RomClientJsonRpcClient.java:147)
        at org.kurento.client.internal.client.RomManager.create(RomManager.java:59)
        at org.kurento.client.internal.client.RomManager.createWithKurentoObject(RomManager.java:257)
        at org.kurento.client.AbstractBuilder.build(AbstractBuilder.java:65)
        at io.openvidu.server.kurento.endpoint.PublisherEndpoint.internalEndpointInitialization(PublisherEndpoint.java:84)
        at io.openvidu.server.kurento.endpoint.MediaEndpoint.createEndpoint(MediaEndpoint.java:185)
        at io.openvidu.server.kurento.core.KurentoParticipant.createPublishingEndpoint(KurentoParticipant.java:104)
        at io.openvidu.server.kurento.core.KurentoSessionManager.publishVideo(KurentoSessionManager.java:265)
        at io.openvidu.server.rpc.RpcHandler.publishVideo(RpcHandler.java:296)
        at io.openvidu.server.rpc.RpcHandler.handleRequest(RpcHandler.java:123)
        at org.kurento.jsonrpc.internal.JsonRpcHandlerManager.handleRequest(JsonRpcHandlerManager.java:128)
        at org.kurento.jsonrpc.internal.server.ProtocolManager$3.run(ProtocolManager.java:218)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException: null
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:411)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:84)
        at org.kurento.jsonrpc.client.AbstractJsonRpcClientWebSocket.internalSendRequestWebSocket(AbstractJsonRpcClientWebSocket.java:377)
        ... 21 common frames omitted
```

**Comment by micaelgallego** [comment]
We have released a new version of OpenVidu (2.13) with important stability fixes. 

Please update from 2.11 to 2.13 to see if error still happens. 

I'm closing the bug for now. Please reopen if error still appear.
