### ISSUE TITLE
RPCNotificationService exception with closed ws

### ISSUE THREAD

**Issue by techcouncilbox** [OpenVidu/openvidu#459]
**Describe the bug**
Possible Bug is described in https://openvidu.discourse.group/t/rpcnotificationservice-exception-with-closed-ws/623/6

Logs are attached in thread

Sorry for the spam but maybe it is better place to check that.

**Expected behavior**
All rpc calls should be called with opened rpc websocket. 
 
**Wrong current behavior**
RPCNotificationService exception with closed ws when sending messages. Logs are attached 

**OpenVidu tutorial where to replicate the error**

**Client device info (if applicable)**
Chrome 81 with PC (windows, Mac, Unix)

**Screenshots**

**Additional context**

**Comment by techcouncilbox** [comment]
It looks like 2 threads are triying to perform operations and obtains unconsistent info (highlighted in orange when second thread is disconnecting and after that error arises).

![image](https://user-images.githubusercontent.com/17164419/80963937-4535dc00-8e10-11ea-9193-0b1fc0f0c0f5.png)

Maybe these variables in KurentoParticipant require a ReadLock in getter methods:

![image](https://user-images.githubusercontent.com/17164419/80963783-f12af780-8e0f-11ea-94a4-984fe3de3b5c.png)

**Comment by syamgk** [comment]
2020-06-09T07:10:24.356450448Z [ERROR] 2020-06-09 07:10:24,356 [TaskScheduler-1] io.openvidu.server.rpc.RpcNotificationService - Exception sending notification 'participantLeft': {"connectionId":"con_YBufcX3oh9","reason":"networkDisconnect"} to participant with private id jnbpa4mmjocr4775mlajbc7239
2020-06-09T07:10:24.356465126Z org.kurento.commons.exception.KurentoException: Exception while sending message '{"method":"participantLeft","params":{"connectionId":"con_YBufcX3oh9","reason":"networkDisconnect"},"jsonrpc":"2.0"}' to websocket with native sessionId 'b0420f63-6fd4-24a8-3213-edca021afe49'
2020-06-09T07:10:24.356471002Z  at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.sendRequestWebSocket(WebSocketServerSession.java:123)
2020-06-09T07:10:24.356475656Z  at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.access$000(WebSocketServerSession.java:49)
2020-06-09T07:10:24.356480179Z  at org.kurento.jsonrpc.internal.ws.WebSocketServerSession$1.internalSendRequest(WebSocketServerSession.java:74)
2020-06-09T07:10:24.356484302Z  at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendRequest(JsonRpcRequestSenderHelper.java:75)
2020-06-09T07:10:24.356488498Z  at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendNotification(JsonRpcRequestSenderHelper.java:156)
2020-06-09T07:10:24.356492392Z  at org.kurento.jsonrpc.internal.server.ServerSession.sendNotification(ServerSession.java:121)
2020-06-09T07:10:24.356496311Z  at io.openvidu.server.rpc.RpcNotificationService.sendNotification(RpcNotificationService.java:105)
2020-06-09T07:10:24.356500137Z  at io.openvidu.server.core.SessionEventsHandler.onParticipantLeft(SessionEventsHandler.java:181)
2020-06-09T07:10:24.356504123Z  at io.openvidu.server.kurento.core.KurentoSessionManager.leaveRoom(KurentoSessionManager.java:247)
2020-06-09T07:10:24.356516953Z  at io.openvidu.server.kurento.core.KurentoSessionManager.evictParticipant(KurentoSessionManager.java:628)
2020-06-09T07:10:24.356520687Z  at io.openvidu.server.rpc.RpcHandler.leaveRoomAfterConnClosed(RpcHandler.java:631)
2020-06-09T07:10:24.356524609Z  at io.openvidu.server.rpc.RpcHandler.afterConnectionClosed(RpcHandler.java:684)
2020-06-09T07:10:24.356528339Z  at org.kurento.jsonrpc.internal.JsonRpcHandlerManager.afterConnectionClosed(JsonRpcHandlerManager.java:65)
2020-06-09T07:10:24.356532099Z  at org.kurento.jsonrpc.internal.server.ProtocolManager.closeSession(ProtocolManager.java:446)
2020-06-09T07:10:24.356535857Z  at org.kurento.jsonrpc.internal.server.ProtocolManager$4.run(ProtocolManager.java:421)
2020-06-09T07:10:24.356540419Z  at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
2020-06-09T07:10:24.356544446Z  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-06-09T07:10:24.356548289Z  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-06-09T07:10:24.356551966Z  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
2020-06-09T07:10:24.356556513Z  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
2020-06-09T07:10:24.356560271Z  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-06-09T07:10:24.356563893Z  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-06-09T07:10:24.356567493Z  at java.lang.Thread.run(Thread.java:748)
2020-06-09T07:10:24.356571448Z Caused by: java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed
2020-06-09T07:10:24.356575246Z  at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:430)
2020-06-09T07:10:24.356579048Z  at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:309)
2020-06-09T07:10:24.356582746Z  at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:250)
2020-06-09T07:10:24.356586570Z  at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendPartialString(WsRemoteEndpointImplBase.java:223)
2020-06-09T07:10:24.356590470Z  at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:49)
2020-06-09T07:10:24.356594367Z  at org.springframework.web.socket.adapter.standard.StandardWebSocketSession.sendTextMessage(StandardWebSocketSession.java:215)
2020-06-09T07:10:24.356598140Z  at org.springframework.web.socket.adapter.AbstractWebSocketSession.sendMessage(AbstractWebSocketSession.java:106)
2020-06-09T07:10:24.356601910Z  at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.sendRequestWebSocket(WebSocketServerSession.java:119)
2020-06-09T07:10:24.356609273Z  ... 22 common frames omitted
```

**Comment by syamgk** [comment]
```
2020-06-09T07:10:24.356450448Z [ERROR] 2020-06-09 07:10:24,356 [TaskScheduler-1] io.openvidu.server.rpc.RpcNotificationService - Exception sending notification 'participantLeft': {"connectionId":"con_XXXXXX","reason":"networkDisconnect"} to participant with private id xxxxxxxxxxxxxxx
2020-06-09T07:10:24.356465126Z org.kurento.commons.exception.KurentoException: Exception while sending message '{"method":"participantLeft","params":{"connectionId":"con_XXXXXX","reason":"networkDisconnect"},"jsonrpc":"2.0"}' to websocket with native sessionId 'xxxxxxxxx-xxxxx-xxxx-xxxx'
2020-06-09T07:10:24.356471002Z  at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.sendRequestWebSocket(WebSocketServerSession.java:123)
2020-06-09T07:10:24.356475656Z  at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.access$000(WebSocketServerSession.java:49)
2020-06-09T07:10:24.356480179Z  at org.kurento.jsonrpc.internal.ws.WebSocketServerSession$1.internalSendRequest(WebSocketServerSession.java:74)
2020-06-09T07:10:24.356484302Z  at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendRequest(JsonRpcRequestSenderHelper.java:75)
2020-06-09T07:10:24.356488498Z  at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendNotification(JsonRpcRequestSenderHelper.java:156)
2020-06-09T07:10:24.356492392Z  at org.kurento.jsonrpc.internal.server.ServerSession.sendNotification(ServerSession.java:121)
2020-06-09T07:10:24.356496311Z  at io.openvidu.server.rpc.RpcNotificationService.sendNotification(RpcNotificationService.java:105)
2020-06-09T07:10:24.356500137Z  at io.openvidu.server.core.SessionEventsHandler.onParticipantLeft(SessionEventsHandler.java:181)
2020-06-09T07:10:24.356504123Z  at io.openvidu.server.kurento.core.KurentoSessionManager.leaveRoom(KurentoSessionManager.java:247)
2020-06-09T07:10:24.356516953Z  at io.openvidu.server.kurento.core.KurentoSessionManager.evictParticipant(KurentoSessionManager.java:628)
2020-06-09T07:10:24.356520687Z  at io.openvidu.server.rpc.RpcHandler.leaveRoomAfterConnClosed(RpcHandler.java:631)
2020-06-09T07:10:24.356524609Z  at io.openvidu.server.rpc.RpcHandler.afterConnectionClosed(RpcHandler.java:684)
2020-06-09T07:10:24.356528339Z  at org.kurento.jsonrpc.internal.JsonRpcHandlerManager.afterConnectionClosed(JsonRpcHandlerManager.java:65)
2020-06-09T07:10:24.356532099Z  at org.kurento.jsonrpc.internal.server.ProtocolManager.closeSession(ProtocolManager.java:446)
2020-06-09T07:10:24.356535857Z  at org.kurento.jsonrpc.internal.server.ProtocolManager$4.run(ProtocolManager.java:421)
2020-06-09T07:10:24.356540419Z  at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
2020-06-09T07:10:24.356544446Z  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020-06-09T07:10:24.356548289Z  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-06-09T07:10:24.356551966Z  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
2020-06-09T07:10:24.356556513Z  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
2020-06-09T07:10:24.356560271Z  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020-06-09T07:10:24.356563893Z  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020-06-09T07:10:24.356567493Z  at java.lang.Thread.run(Thread.java:748)
2020-06-09T07:10:24.356571448Z Caused by: java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed
2020-06-09T07:10:24.356575246Z  at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:430)
2020-06-09T07:10:24.356579048Z  at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:309)
2020-06-09T07:10:24.356582746Z  at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:250)
2020-06-09T07:10:24.356586570Z  at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendPartialString(WsRemoteEndpointImplBase.java:223)
2020-06-09T07:10:24.356590470Z  at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:49)
2020-06-09T07:10:24.356594367Z  at org.springframework.web.socket.adapter.standard.StandardWebSocketSession.sendTextMessage(StandardWebSocketSession.java:215)
2020-06-09T07:10:24.356598140Z  at org.springframework.web.socket.adapter.AbstractWebSocketSession.sendMessage(AbstractWebSocketSession.java:106)
2020-06-09T07:10:24.356601910Z  at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.sendRequestWebSocket(WebSocketServerSession.java:119)
2020-06-09T07:10:24.356609273Z  ... 22 common frames omitted
```

**Comment by viktara** [comment]
We're facing constant session crashes for users with this error on the latest release of openvidu.
After a restart everything seems to work ok for a day or so and then users meetings start failing with the above error being thrown on the server.
We're restarting daily at the moment.
Any pointers on how to debug this would be appreciated.

**Comment by micaelgallego** [comment]
@viktara can you describe your problem in more detail? Can you share an entire OpenVidu server log?

**Comment by syam-tbl** [comment]
Hi @micaelgallego , 
Here is the link to more detail logs
https://cloud.techblue.co.uk/s/8PLdi1bP1WllqGb/download
Kindly let us know if you need any further information

**Comment by viktara** [comment]
@micaelgallego 
we're still experiencing multiple user session crashes each day. The only work around so far is to restart the containers and the problem goes away for a while.
any pointers on where to debug would be appreciated.
we're digging deeper and profiling at the moment, but are surprised that this issue is not effecting anyone else or in fact your pro customers.
are you aware of any other occurrences of this issue or can you give us any further pointers here?

**Comment by pabloFuente** [comment]
Hi,

We are not experiencig this kind of issues. I can't think of anybody with this same problem. How is your CPU load behavior? If your system is overloaded this kind of issues may appear.

**Comment by viktara** [comment]
Everything on that front seems fine, no cpu spikes, tons of unused memory. The instance is big and we have a small number of users, so I don't think it can be related to that.

A long shot, but we're going to disable the session garbage collector just in case that is causing an issue.

**Comment by viktara** [comment]
We have set up a new instance exactly as per the deploymet guide and started load testing using KITE. We get the same issue with the new instance, the session disconnects all users and throws the same error on the server.
There is very little load on the system and it seems to happen even with very few users in a conference.
We're creating a screencast in case you want to have a look.
Could you help us with some pointers of where to look next?

**Comment by viktara** [comment]
@syam-tbl confirmed that we are not hitting 200 threads, so this issue does not seem linked to #476

**Comment by viktara** [comment]
@micaelgallego @pabloFuente we upgraded to the latest release and ran load tests again, but the error still occurs

**Comment by micaelgallego** [comment]
Thank you for reporting. We will take a look to see what happens

**Comment by pabloFuente** [comment]
Let's sort out a bit the problems described here.

This issue was started by @techcouncilbox refering a post message titled **"RPCNotificationService exception with closed ws"**.

The suggestion made by this user was some kind of concurrency problem, but this doesn't really make sense. This message/exception appears when some client disconnects its websocket to OpenVidu Server. If this happens and OpenVidu is in the middle of notifying users about some event of the session, then it will throw this error. So the error is not a problem _per se_, it simply informs about the impossibility of sending a message to a closed client.

Then @viktara posted a new message talking about this same error. We discovered a possible bug that was affecting the amount of threads available for Tomcat in OpenVidu Server, but this seems not to be the real problem here according to https://github.com/OpenVidu/openvidu/issues/459#issuecomment-654159627.

So, from this point we need a way of replicating @viktara issue. Please, can you tell us how is your exact deployment? Did you deployed in AWS or On Premises? If it is the last one, release 2.15.0 brings a beautiful command that you can execute in your OpenVidu installation folder (default to `/opt/openvidu`) to get that information:

**`./openvidu version`**

Also, if you are using a particular Cloud Provider to deploy OpenVidu On Premises, tell us which. 

After having all of your deployment information, we need a way of replicating the problem using an application. WHen do you get the error? Connecting 5,6,7.... users at a time all of them publishing and subscribing to each other? What is th architecture of your sessions?

Regards.

**Comment by viktara** [comment]
@pabloFuente Yeah - it seems that the error is as you say and doesn't give us much information about why the video sessions die.
As for the environment, we first deployed on aws and then tried another set up on digital ocean.

We have run load tests against both 2.14 and 2.15 and see the same behaviour in both and are using the openvidu-call application as our front end. I guess the problem could arise there.
@syam-tbl is running the load tests and has more information so I'll leave him to pitch in here too.

**Comment by syam-tbl** [comment]
@pabloFuente as @viktara mentioned we tested 

- 2.14.0 on AWS
OS : Ubuntu 18.04.3 LTS
Docker version: 19.03.8
docker-compose version 1.25.5,

- both 2.14.0 and 2.15.0 on Digital Ocean.
OS : Ubuntu 18.04.3 LTS
Docker version: 19.03.1
docker-compose version 1.26.0

We were using KITE for running the automated test. 
https://github.com/CoSMoSoftware/KITE-Sample-Tests/tree/master/KITE-OpenVidu-Test

**Comment by viktara** [comment]
@syam-tbl can you execute ./openvidu version as suggested by @pabloFuente too please?

**Comment by syam-tbl** [comment]
Sure, here is the output of that one
```
$ ./openvidu version

Openvidu Information:

  Installation Type: On Premises
  Openvidu Version: 2.15.0
  Openvidu Call Version: 2.15.0

System Information:

  Linux Version:
    - Description:      Ubuntu 18.04.3 LTS
  Docker Version: 19.03.1
  Docker Compose Version: 1.26.0

Installation Information:

  Installation Folder: /opt/openvidu
  Installation Folder Tree:

         |-docker-compose.override.yml
         |-openvidu
         |-docker-compose.yml
         |-.env
         |-readme.md
         |-owncert
         | |-certificate.key
         | |-certificate.cert

Docker Running Services:

  CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS                  PORTS                    NAMES
        fc9e99d30dc5        openvidu/openvidu-coturn:1.0.0        "/bin/sh -c /usr/loc_"   47 hours ago        Up 47 hours                                      openvidu_coturn_1
        c711e9417269        redis:5.0.7                           "docker-entrypoint.s_"   47 hours ago        Up 47 hours                                      openvidu_redis_1
        a6aac117e87b        openvidu/openvidu-call:2.15.0         "docker-entrypoint.s_"   47 hours ago        Up 47 hours             0.0.0.0:5442->5000/tcp   openvidu_app_1
        04b07d9aefc3        openvidu/openvidu-server:2.15.0       "/bin/bash -c 'expor_"   47 hours ago        Up 47 hours                                      openvidu_openvidu-server_1
        ba91866204e2        kurento/kurento-media-server:6.14.0   "/entrypoint.sh"         47 hours ago        Up 47 hours (healthy)                            openvidu_kms_1
        83f26c02a47f        openvidu/openvidu-proxy:2.0.0         "/bin/sh -c /usr/loc_"   47 hours ago        Up 47 hours                                      openvidu_nginx_1
```
