### ISSUE TITLE
OpenVidu Server tomcat may be running out of threads (GET /api/sessions)

### ISSUE THREAD

**Issue by pabloFuente** [OpenVidu/openvidu#476]
**Describe the bug**
It seems that there might be some kind of corner case where OpenVidu Server tomcat threads are getting stuck when calling REST API operation `GET /api/sessions`. The default 200 threads are being taken and when the upper limit is reached no more REST API operations can be attended.

**Expected behavior**
REST API should never stop responding.

**Wrong current behavior**
REST API can stop responding under some strange conditions that we have only seen once and that we cannot reliably replicate.

**OpenVidu tutorial where to replicate the error**
Replication of this bug has been proven to be very difficult. We have extended OpenVidu Server logs in image `openvidu/openvidu-server:2.14.1-beta2` (**[LINK](https://hub.docker.com/layers/openvidu/openvidu-server/2.14.1-beta2/images/sha256-762b4e2874b008692da7688eb12a4e68af636ea865a915bfcb13a2f4366c6c24?context=explore)**) and `openvidu/openvidu-server-pro:2.14.1-beta2` (**[LINK](https://hub.docker.com/layers/openvidu/openvidu-server-pro/2.14.1-beta2/images/sha256-674c7e55944dc487b8ec8b626a9f8d5126808b1e09dc650a0b7a9b415d7b3821?context=explore)**) 

**OpenVidu deployment info**
On Premises deployment ([CE](https://docs.openvidu.io/en/2.14.0/deployment/deploying-on-premises/) and [PRO](https://docs.openvidu.io/en/2.14.0/openvidu-pro/deployment/on-premises/))

**Client device info (if applicable)**
_Not relevant_

**Screenshots**
_Not relevant_

**Additional context**
***IMPORTANT***: this is the log that can be seen when tomcat runs out of threads. If string **`-exec-200]`** can be found in openvidu-server log, then it means that tomcat has reached is upper limit.

```
[INFO] 2020-05-05 12:27:48,557 [0-5443-exec-199] io.openvidu.server.rest.SessionRestController - REST API: GET /api/sessions

...

[INFO] 2020-05-05 12:28:13,578 [0-5443-exec-198] io.openvidu.server.rest.SessionRestController - REST API: GET /api/sessions

...

[INFO] 2020-05-05 12:28:18,590 [0-5443-exec-200] io.openvidu.server.rest.SessionRestController - REST API: GET /api/sessions
```

**Comment by syam-tbl** [comment]
@pabloFuente  Do you think this bug is connected to https://github.com/OpenVidu/openvidu/issues/459 ?
This is the log snippet from our instance 
```
INFO] 2020-06-30 12:29:05,258 [entExec-e2-t678] io.openvidu.server.kurento.core.KurentoParticipantEndpointConfig - KMS event [MediaFlowOutStateChange] -> endpoint: str_CAM_ByoQ_con_H72afUa4q9 (publisher) | state: NOT_FLOWING | pad: default | mediaType: AUDIO | timestamp: 1593520145257
[INFO] 2020-06-30 12:29:05,400 [0.0-5443-exec-2] io.openvidu.server.rest.SessionRestController - REST API: POST /api/sessions {customSessionId=OpenVidu74986d41cb8a41ae92a6cc5251947d48}
[INFO] 2020-06-30 12:29:05,478 [0.0-5443-exec-3] io.openvidu.server.rest.SessionRestController - REST API: POST /api/tokens {session=OpenVidu74986d41cb8a41ae92a6cc5251947d48}
[INFO] 2020-06-30 12:29:05,478 [0.0-5443-exec-3] io.openvidu.server.coturn.CoturnCredentialsService - Creating COTURN user
[INFO] 2020-06-30 12:29:05,490 [0.0-5443-exec-3] io.openvidu.server.coturn.CoturnCredentialsService - COTURN user created: true
[INFO] 2020-06-30 12:29:05,491 [0.0-5443-exec-3] io.openvidu.server.core.Session - Token created { Session: OpenVidu74986d41cb8a41ae92a6cc5251947d48 | Tokens: [wss://om-beta.techblue.co.uk?sessionId=OpenVidu74986d41cb8a41ae92a6cc5251947d48&token=tok_KXXXXXXXXXX&role=PUBLISHER&version=2.14.0&coturnIp=XXX.XXX.XX.X&turnUsername=XXX8J&turnCredential=XXXX] }
[INFO] 2020-06-30 12:29:05,801 [0.0-5443-exec-8] io.openvidu.server.rest.SessionRestController - REST API: POST /api/sessions {customSessionId=OpenVidu74986d41cb8a41ae92a6cc5251947d48}
[INFO] 2020-06-30 12:29:05,831 [entExec-e2-t678] io.openvidu.server.kurento.core.KurentoParticipantEndpointConfig - KMS event [MediaFlowInStateChange] -> endpoint: con_WpvrWrTnhl_str_CAM_ByoQ_con_H72afUa4q9 (subscriber) | state: NOT_FLOWING | pad: default | mediaType: AUDIO | timestamp: 1593520145830
[INFO] 2020-06-30 12:29:05,831 [entExec-e2-t676] io.openvidu.server.kurento.core.KurentoParticipantEndpointConfig - KMS event [MediaFlowInStateChange] -> endpoint: con_WpvrWrTnhl_str_CAM_ByoQ_con_H72afUa4q9 (subscriber) | state: NOT_FLOWING | pad: default | mediaType: VIDEO | timestamp: 1593520145830
[INFO] 2020-06-30 12:29:05,879 [0.0-5443-exec-6] io.openvidu.server.rest.SessionRestController - REST API: POST /api/tokens {session=OpenVidu74986d41cb8a41ae92a6cc5251947d48}
[INFO] 2020-06-30 12:29:05,879 [0.0-5443-exec-6] io.openvidu.server.coturn.CoturnCredentialsService - Creating COTURN user
[INFO] 2020-06-30 12:29:05,891 [0.0-5443-exec-6] io.openvidu.server.coturn.CoturnCredentialsService - COTURN user created: true
[INFO] 2020-06-30 12:29:05,895 [0.0-5443-exec-6] io.openvidu.server.core.Session - Token created { Session: OpenVidu74986d41cb8a41ae92a6cc5251947d48 | Tokens: [wss://om-beta.techblue.co.uk?sessionId=OpenVidu74986d41cb8a41ae92a6cc5251947d48&token=tok_K6054wQcrsC1JDdJ&role=PUBLISHER&version=2.14.0&coturnIp=134.209.30.225&turnUsername=L7768J&turnCredential=hbcr9g, wss://om-beta.techblue.co.uk?sessionId=OpenVidu74986d41cb8a41ae92a6cc5251947d48&token=XXXXXXXXX&role=PUBLISHER&version=2.14.0&coturnIp=1XX.2XX.XX.2XX&turnUsername=XXXXX&turnCredential=xxxxo] }
[INFO] 2020-06-30 12:29:06,316 [entExec-e2-t676] io.openvidu.server.kurento.core.KurentoParticipantEndpointConfig - KMS event [MediaFlowOutStateChange] -> endpoint: str_CAM_Yl8l_con_TybyTlswiQ (publisher) | state: NOT_FLOWING | pad: default | mediaType: AUDIO | timestamp: 1593520146315
[INFO] 2020-06-30 12:29:06,387 [entExec-e2-t676] io.openvidu.server.kurento.core.KurentoParticipantEndpointConfig - KMS event [MediaFlowOutStateChange] -> endpoint: str_CAM_Yl8l_con_TybyTlswiQ (publisher) | state: NOT_FLOWING | pad: default | mediaType: VIDEO | timestamp: 1593520146386
[INFO] 2020-06-30 12:29:06,446 [TaskScheduler-1] io.openvidu.server.rpc.RpcHandler - After connection closed for WebSocket session: ml9ff9ckfajn20ob69h0q7oeu7 - Status: null
[INFO] 2020-06-30 12:29:06,446 [TaskScheduler-1] io.openvidu.server.rpc.RpcNotificationService - Closed session for participant with private id ml9ff9ckfajn20ob69h0q7oeu7
[INFO] 2020-06-30 12:29:06,446 [TaskScheduler-1] io.openvidu.server.rpc.RpcNotificationService - <PRIVATE_ID, RPC_CONNECTION>: {g14fq4d2oefv817jjklv7i3skr=io.openvidu.server.rpc.RpcConnection@4f1081c1, q1geohft7i2fsiq98kndtmc8fp=io.openvidu.server.rpc.RpcConnection@4b2f1cfb, 31bp6dvegq6ettd5hc8kt4g94k=io.openvidu.server.rpc.RpcConnection@6e0274b5, m9mtj49sf1d6es8ib49rf03qja=io.openvidu.server.rpc.RpcConnection@5b957022, o6lsflj09qcbo5i27u6ivnt7h3=io.openvidu.server.rpc.RpcConnection@7cd837e8, lt9iduvrrfa465se6ct262rj04=io.openvidu.server.rpc.RpcConnection@97e9c50}
[INFO] 2020-06-30 12:29:06,446 [TaskScheduler-1] io.openvidu.server.rpc.RpcHandler - Evicting participant with private id ml9ff9ckfajn20ob69h0q7oeu7 because its websocket unexpectedly closed in the client side
[INFO] 2020-06-30 12:29:06,446 [TaskScheduler-1] io.openvidu.server.kurento.core.KurentoSessionManager - Request [LEAVE_ROOM] for participant con_DCeyepAoiT of session OpenVidu74986d41cb8a41ae92a6cc5251947d48 with reason networkDisconnect
[INFO] 2020-06-30 12:29:06,446 [TaskScheduler-1] io.openvidu.server.kurento.core.KurentoSession - PARTICIPANT con_DCeyepAoiT: Leaving session OpenVidu74986d41cb8a41ae92a6cc5251947d48
[INFO] 2020-06-30 12:29:06,446 [TaskScheduler-1] io.openvidu.server.kurento.core.KurentoParticipant - PARTICIPANT con_H72afUa4q9: cancel receiving media from con_DCeyepAoiT
[WARN] 2020-06-30 12:29:06,446 [TaskScheduler-1] io.openvidu.server.kurento.core.KurentoParticipant - PARTICIPANT con_H72afUa4q9: Trying to cancel receiving video from user con_DCeyepAoiT. But there is no such subscriber endpoint.
[INFO] 2020-06-30 12:29:06,446 [TaskScheduler-1] io.openvidu.server.kurento.core.KurentoParticipant - PARTICIPANT con_McMxeSbUPY: cancel receiving media from con_DCeyepAoiT
[WARN] 2020-06-30 12:29:06,446 [TaskScheduler-1] io.openvidu.server.kurento.core.KurentoParticipant - PARTICIPANT con_McMxeSbUPY: Trying to cancel receiving video from user con_DCeyepAoiT. But there is no such subscriber endpoint.
[INFO] 2020-06-30 12:29:06,446 [TaskScheduler-1] io.openvidu.server.kurento.core.KurentoParticipant - PARTICIPANT con_WpvrWrTnhl: cancel receiving media from con_DCeyepAoiT
[WARN] 2020-06-30 12:29:06,446 [TaskScheduler-1] io.openvidu.server.kurento.core.KurentoParticipant - PARTICIPANT con_WpvrWrTnhl: Trying to cancel receiving video from user con_DCeyepAoiT. But there is no such subscriber endpoint.
[INFO] 2020-06-30 12:29:06,446 [TaskScheduler-1] io.openvidu.server.kurento.core.KurentoParticipant - PARTICIPANT con_TybyTlswiQ: cancel receiving media from con_DCeyepAoiT
[WARN] 2020-06-30 12:29:06,446 [TaskScheduler-1] io.openvidu.server.kurento.core.KurentoParticipant - PARTICIPANT con_TybyTlswiQ: Trying to cancel receiving video from user con_DCeyepAoiT. But there is no such subscriber endpoint.
[INFO] 2020-06-30 12:29:06,446 [TaskScheduler-1] io.openvidu.server.kurento.core.KurentoParticipant - PARTICIPANT con_N5dm1GSKgn: cancel receiving media from con_DCeyepAoiT
[WARN] 2020-06-30 12:29:06,446 [TaskScheduler-1] io.openvidu.server.kurento.core.KurentoParticipant - PARTICIPANT con_N5dm1GSKgn: Trying to cancel receiving video from user con_DCeyepAoiT. But there is no such subscriber endpoint.
[INFO] 2020-06-30 12:29:06,447 [TaskScheduler-1] io.openvidu.server.coturn.CoturnCredentialsService - Deleting COTURN user
[INFO] 2020-06-30 12:29:06,459 [TaskScheduler-1] io.openvidu.server.coturn.CoturnCredentialsService - COTURN user deleted: true
[ERROR] 2020-06-30 12:29:06,460 [TaskScheduler-1] io.openvidu.server.rpc.RpcNotificationService - Exception sending notification 'participantLeft': {"connectionId":"con_DCeyepAoiT","reason":"networkDisconnect"} to participant with private id o6lsflj09qcbo5i27u6ivnt7h3
org.kurento.commons.exception.KurentoException: Exception while sending message '{"method":"participantLeft","params":{"connectionId":"con_DCeyepAoiT","reason":"networkDisconnect"},"jsonrpc":"2.0"}' to websocket with native sessionId 'e5127a08-550f-d191-c69f-de21f425b68c'
        at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.sendRequestWebSocket(WebSocketServerSession.java:123)
        at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.access$000(WebSocketServerSession.java:49)
        at org.kurento.jsonrpc.internal.ws.WebSocketServerSession$1.internalSendRequest(WebSocketServerSession.java:74)
        at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendRequest(JsonRpcRequestSenderHelper.java:75)
        at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendNotification(JsonRpcRequestSenderHelper.java:156)
        at org.kurento.jsonrpc.internal.server.ServerSession.sendNotification(ServerSession.java:121)
        at io.openvidu.server.rpc.RpcNotificationService.sendNotification(RpcNotificationService.java:105)
        at io.openvidu.server.core.SessionEventsHandler.onParticipantLeft(SessionEventsHandler.java:181)
        at io.openvidu.server.kurento.core.KurentoSessionManager.leaveRoom(KurentoSessionManager.java:247)
        at io.openvidu.server.kurento.core.KurentoSessionManager.evictParticipant(KurentoSessionManager.java:628)
        at io.openvidu.server.rpc.RpcHandler.leaveRoomAfterConnClosed(RpcHandler.java:631)
        at io.openvidu.server.rpc.RpcHandler.afterConnectionClosed(RpcHandler.java:684)
        at org.kurento.jsonrpc.internal.JsonRpcHandlerManager.afterConnectionClosed(JsonRpcHandlerManager.java:65)
        at org.kurento.jsonrpc.internal.server.ProtocolManager.closeSession(ProtocolManager.java:446)
        at org.kurento.jsonrpc.internal.server.ProtocolManager$4.run(ProtocolManager.java:421)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: The WebSocket session [56] has been closed and no method (apart from close()) may be called on a closed session
        at org.apache.tomcat.websocket.WsSession.checkState(WsSession.java:836)
        at org.apache.tomcat.websocket.WsSession.getBasicRemote(WsSession.java:433)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketSession.sendTextMessage(StandardWebSocketSession.java:215)
        at org.springframework.web.socket.adapter.AbstractWebSocketSession.sendMessage(AbstractWebSocketSession.java:106)
        at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.sendRequestWebSocket(WebSocketServerSession.java:119)
        ... 22 common frames omitted
[ERROR] 2020-06-30 12:29:06,461 [TaskScheduler-1] io.openvidu.server.rpc.RpcNotificationService - Exception sending notification 'participantLeft': {"connectionId":"con_DCeyepAoiT","reason":"networkDisconnect"} to participant with private id g14fq4d2oefv817jjklv7i3skr
org.kurento.commons.exception.KurentoException: Exception while sending message '{"method":"participantLeft","params":{"connectionId":"con_DCeyepAoiT","reason":"networkDisconnect"},"jsonrpc":"2.0"}' to websocket with native sessionId '43bacf68-6ffa-64d7-bf77-5e4bcef5d7c5'
        at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.sendRequestWebSocket(WebSocketServerSession.java:123)
        at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.access$000(WebSocketServerSession.java:49)
        at org.kurento.jsonrpc.internal.ws.WebSocketServerSession$1.internalSendRequest(WebSocketServerSession.java:74)
        at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendRequest(JsonRpcRequestSenderHelper.java:75)
        at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendNotification(JsonRpcRequestSenderHelper.java:156)
        at org.kurento.jsonrpc.internal.server.ServerSession.sendNotification(ServerSession.java:121)
        at io.openvidu.server.rpc.RpcNotificationService.sendNotification(RpcNotificationService.java:105)
        at io.openvidu.server.core.SessionEventsHandler.onParticipantLeft(SessionEventsHandler.java:181)
        at io.openvidu.server.kurento.core.KurentoSessionManager.leaveRoom(KurentoSessionManager.java:247)
        at io.openvidu.server.kurento.core.KurentoSessionManager.evictParticipant(KurentoSessionManager.java:628)
        at io.openvidu.server.rpc.RpcHandler.leaveRoomAfterConnClosed(RpcHandler.java:631)
        at io.openvidu.server.rpc.RpcHandler.afterConnectionClosed(RpcHandler.java:684)
        at org.kurento.jsonrpc.internal.JsonRpcHandlerManager.afterConnectionClosed(JsonRpcHandlerManager.java:65)
        at org.kurento.jsonrpc.internal.server.ProtocolManager.closeSession(ProtocolManager.java:446)
        at org.kurento.jsonrpc.internal.server.ProtocolManager$4.run(ProtocolManager.java:421)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: The WebSocket session [52] has been closed and no method (apart from close()) may be called on a closed session
        at org.apache.tomcat.websocket.WsSession.checkState(WsSession.java:836)
        at org.apache.tomcat.websocket.WsSession.getBasicRemote(WsSession.java:433)
        at org.springframework.web.socket.adapter.standard.StandardWebSocketSession.sendTextMessage(StandardWebSocketSession.java:215)
        at org.springframework.web.socket.adapter.AbstractWebSocketSession.sendMessage(AbstractWebSocketSession.java:106)
        at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.sendRequestWebSocket(WebSocketServerSession.java:119)
        ... 22 common frames omitted
[ERROR] 2020-06-30 12:29:06,461 [TaskScheduler-1] io.openvidu.server.rpc.RpcNotificationService - Exception sending notification 'participantLeft': {"connectionId":"con_DCeyepAoiT","reason":"networkDisconnect"} to participant with private id q1geohft7i2fsiq98kndtmc8fp
org.kurento.commons.exception.KurentoException: Exception while sending message '{"method":"participantLeft","params":{"connectionId":"con_DCeyepAoiT","reason":"networkDisconnect"},"jsonrpc":"2.0"}' to websocket with native sessionId '16bbf9c1-fe85-e544-0b5d-29e8b66f08a8'
        at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.sendRequestWebSocket(WebSocketServerSession.java:123)
        at org.kurento.jsonrpc.internal.ws.WebSocketServerSession.access$000(WebSocketServerSession.java:49)
        at org.kurento.jsonrpc.internal.ws.WebSocketServerSession$1.internalSendRequest(WebSocketServerSession.java:74)
        at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendRequest(JsonRpcRequestSenderHelper.java:75)
        at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper.sendNotification(JsonRpcRequestSenderHelper.java:156)
        at org.kurento.jsonrpc.internal.server.ServerSession.sendNotification(ServerSession.java:121)
        at io.openvidu.server.rpc.RpcNotificationService.sendNotification(RpcNotificationService.java:105)
        at io.openvidu.server.core.SessionEventsHandler.onParticipantLeft(SessionEventsHandler.java:181)
        at io.openvidu.server.kurento.core.KurentoSessionManager.leaveRoom(KurentoSessionManager.java:247)
        at io.openvidu.server.kurento.core.KurentoSessionManager.evictParticipant(KurentoSessionManager.java:628)
        at io.openvidu.server.rpc.RpcHandler.leaveRoomAfterConnClosed(RpcHandler.java:631)
        at io.openvidu.server.rpc.RpcHandler.afterConnectionClosed(RpcHandler.java:684)
        at org.kurento.jsonrpc.internal.JsonRpcHandlerManager.afterConnectionClosed(JsonRpcHandlerManager.java:65)
        at org.kurento.jsonrpc.internal.server.ProtocolManager.closeSession(ProtocolManager.java:446)
        at org.kurento.jsonrpc.internal.server.ProtocolManager$4.run(ProtocolManager.java:421)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: The WebSocket session [54] has been closed and no method (apart from close()) may be called on a closed session
        at org.apache.tomcat.websocket.WsSession.checkState(WsSession.java:836)
        at org.apache.tomcat.websocket.WsSession.getBasicRemote(WsSession.java:433)
```
