### ISSUE TITLE
OPENVIDU-Server 2.14.0 Doesn't work properly following On premises Deployment

### ISSUE THREAD

**Issue by pocce90** [OpenVidu/openvidu#491]
**Describe the bug**
After following on permises deployment guide, openvidu test page doesn't work. The same instruction used istalling openvidu 2.13.0 works well. Creating a session in test page it seems working well, but when I try to enter with another user it seems that user creates another session. After few seconds this error appears:
There was an error getting the token:
`<html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx/1.18.0</center> </body> </html> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page -->`

I get logs from docker-compose logs -f app

```
app_1              | Session ID received { sessionId: 'qqqq' }
app_1              | Requesting session to  https://[my.domain.hidden]:443/api/sessions
app_1              | CALL_OPENVIDU_CERTTYPE owncert
app_1              | Requesting token to  https://[my.domain.hidden]:443/api/tokens
app_1              | CALL_OPENVIDU_CERTTYPE owncert
app_1              | Error: unable to verify the first certificate
app_1              |     at TLSSocket.onConnectSecure (_tls_wrap.js:1474:34)
app_1              |     at TLSSocket.emit (events.js:310:20)
app_1              |     at TLSSocket._finishInit (_tls_wrap.js:917:8)
app_1              |     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:687:12) {
app_1              |   code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
app_1              |   config: {
app_1              |     url: 'https://[my.domain.hidden]:443/api/tokens',
app_1              |     method: 'post',
app_1              |     data: '{"session":"qqqq"}',
app_1              |     headers: {
app_1              |       Accept: 'application/json, text/plain, */*',
app_1              |       'Content-Type': 'application/json',
app_1              |       Authorization: 'Basic T1BFTlZJRFVBUFA6U0VDUkVU',
app_1              |       'User-Agent': 'axios/0.19.2',
app_1              |       'Content-Length': 18
app_1              |     },
app_1              |     transformRequest: [ [Function] ],
app_1              |     transformResponse: [ [Function] ],
app_1              |     timeout: 0,
app_1              |     adapter: [Function],
app_1              |     xsrfCookieName: 'XSRF-TOKEN',
app_1              |     xsrfHeaderName: 'X-XSRF-TOKEN',
app_1              |     maxContentLength: -1,
app_1              |     validateStatus: [Function: validateStatus]
app_1              |   },
app_1              |   request: Writable {
app_1              |     _writableState: WritableState {
app_1              |       objectMode: false,
app_1              |       highWaterMark: 16384,
app_1              |       finalCalled: false,
app_1              |       needDrain: false,
app_1              |       ending: false,
app_1              |       ended: false,
app_1              |       finished: false,
app_1              |       destroyed: false,
app_1              |       decodeStrings: true,
app_1              |       defaultEncoding: 'utf8',
app_1              |       length: 0,
app_1              |       writing: false,
app_1              |       corked: 0,
app_1              |       sync: true,
app_1              |       bufferProcessing: false,
app_1              |       onwrite: [Function: bound onwrite],
app_1              |       writecb: null,
app_1              |       writelen: 0,
app_1              |       afterWriteTickInfo: null,
app_1              |       bufferedRequest: null,
app_1              |       lastBufferedRequest: null,
app_1              |       pendingcb: 0,
app_1              |       prefinished: false,
app_1              |       errorEmitted: false,
app_1              |       emitClose: true,
app_1              |       autoDestroy: false,
app_1              |       bufferedRequestCount: 0,
app_1              |       corkedRequestsFree: [Object]
app_1              |     },
app_1              |     writable: true,
app_1              |     _events: [Object: null prototype] {
app_1              |       response: [Function],
app_1              |       error: [Function]
app_1              |     },
app_1              |     _eventsCount: 2,
app_1              |     _maxListeners: undefined,
app_1              |     _options: {
app_1              |       protocol: 'https:',
app_1              |       maxRedirects: 21,
app_1              |       maxBodyLength: 10485760,
app_1              |       path: '/api/tokens',
app_1              |       method: 'POST',
app_1              |       headers: [Object],
app_1              |       agent: undefined,
app_1              |       agents: [Object],
app_1              |       auth: undefined,
app_1              |       hostname: '[my.domain.hidden]',
app_1              |       port: '443',
app_1              |       nativeProtocols: [Object],
app_1              |       pathname: '/api/tokens'
app_1              |     },
app_1              |     _redirectCount: 0,
app_1              |     _redirects: [],
app_1              |     _requestBodyLength: 18,
app_1              |     _requestBodyBuffers: [ [Object] ],
app_1              |     _onNativeResponse: [Function],
app_1              |     _currentRequest: ClientRequest {
app_1              |       _events: [Object: null prototype],
app_1              |       _eventsCount: 6,
app_1              |       _maxListeners: undefined,
app_1              |       outputData: [],
app_1              |       outputSize: 0,
app_1              |       writable: true,
app_1              |       _last: true,
app_1              |       chunkedEncoding: false,
app_1              |       shouldKeepAlive: false,
app_1              |       useChunkedEncodingByDefault: true,
app_1              |       sendDate: false,
app_1              |       _removedConnection: false,
app_1              |       _removedContLen: false,
app_1              |       _removedTE: false,
app_1              |       _contentLength: null,
app_1              |       _hasBody: true,
app_1              |       _trailer: '',
app_1              |       finished: false,
app_1              |       _headerSent: true,
app_1              |       socket: [TLSSocket],
app_1              |       connection: [TLSSocket],
app_1              |       _header: 'POST /api/tokens HTTP/1.1\r\n' +
app_1              |         'Accept: application/json, text/plain, */*\r\n' +
app_1              |         'Content-Type: application/json\r\n' +
app_1              |         'Authorization: Basic T1BFTlZJRFVBUFA6U0VDUkVU\r\n' +
app_1              |         'User-Agent: axios/0.19.2\r\n' +
app_1              |         'Content-Length: 18\r\n' +
app_1              |         'Host: media3.holo-maintenance.com\r\n' +
app_1              |         'Connection: close\r\n' +
app_1              |         '\r\n',
app_1              |       _onPendingData: [Function: noopPendingOutput],
app_1              |       agent: [Agent],
app_1              |       socketPath: undefined,
app_1              |       method: 'POST',
app_1              |       insecureHTTPParser: undefined,
app_1              |       path: '/api/tokens',
app_1              |       _ended: false,
app_1              |       res: null,
app_1              |       aborted: false,
app_1              |       timeoutCb: null,
app_1              |       upgradeOrConnect: false,
app_1              |       parser: null,
app_1              |       maxHeadersCount: null,
app_1              |       reusedSocket: false,
app_1              |       _redirectable: [Circular],
app_1              |       [Symbol(kCapture)]: false,
app_1              |       [Symbol(kNeedDrain)]: false,
app_1              |       [Symbol(corked)]: 0,
app_1              |       [Symbol(kOutHeaders)]: [Object: null prototype]
app_1              |     },
app_1              |     _currentUrl: 'https://[my.domain.hidden]:443/api/tokens',
app_1              |     [Symbol(kCapture)]: false
app_1              |   },
app_1              |   response: undefined,
app_1              |   isAxiosError: true,
app_1              |   toJSON: [Function]
app_1              | }
app_1              | (node:21) UnhandledPromiseRejectionWarning: RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: undefined
app_1              |     at ServerResponse.writeHead (_http_server.js:248:11)
app_1              |     at ServerResponse._implicitHeader (_http_server.js:239:8)
app_1              |     at write_ (_http_outgoing.js:650:9)
app_1              |     at ServerResponse.end (_http_outgoing.js:761:5)
app_1              |     at ServerResponse.C.send (/opt/openvidu-call/openvidu-call-server.js:302:2782)
app_1              |     at p (/opt/openvidu-call/openvidu-call-server.js:320:3586)
app_1              |     at /opt/openvidu-call/openvidu-call-server.js:320:4257
app_1              |     at /opt/openvidu-call/openvidu-call-server.js:320:2946
app_1              |     at Object.throw (/opt/openvidu-call/openvidu-call-server.js:320:3051)
app_1              |     at r (/opt/openvidu-call/openvidu-call-server.js:320:1816)
app_1              | (node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
app_1              | (node:21) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behavior**
the two users connected to the same session will receive and send audio/video from each other

**Wrong current behavior**
each user only sees their own stream

**OpenVidu tutorial where to replicate the error**
This is an EXTREMELY IMPORTANT STEP. If we are able to replicate the error in any of the official [OpenVidu Tutorials](https://github.com/OpenVidu/openvidu-tutorials) or [OpenVidu Demos](https://github.com/OpenVidu), then we will be able to quickly fix it. If you are getting the error in your own application, please try to add the necessary changes to the most similar tutorial so it fails with the same error (try to keep those changes as contained as possible, so that the original tutorial maintains its integrity). Once you have an application to replicate the error, explain in detail the steps to get it like this:
1. Clone repository [...]
2. Compile the application like this [...]
3. Run OpenVidu Server like this [...]
4. Run the application like this [...]
5. Join 1 user... Publish a video stream [...]
6. See error

**OpenVidu deployment info**
How is your OpenVidu Server instance deployed when you get the bug. A couple of possible examples are listed below:
- Docker container as explained in OpenVidu tutorials, run with command `docker run ...` on macOS Catalina 10.15.1
- AWS deployment as explained in OpenVidu Docs (https://docs.openvidu.io/en/stable/deployment/deploying-aws/)
On permises deployment as explained in OpenVidu Docs
(https://docs.openvidu.io/en/2.14.0/deployment/deploying-on-premises/)
Installed in an Azure Virtual Machine (Ubuntu 18.04 LTS)

> **IMPORTANT NOTE**: please, if you think the bug might be related to OpenVidu Server side, specify here if you are also getting the error by using OpenVidu Server Demos instance. This instance is publicly available (use it only for this test, because it is not secure!!!): **URL**: `https://demos.openvidu.io:4443`, **SECRET**: `MY_SECRET`
I get the error in OpenVidu Server Demo

**Client device info (if applicable)**
Describe the client device(s) or platform(s) where you are able to replicate the error. For example:
- Chrome 83.0.4103.61 (Official Build) (64-bit) on Windows 10 (1903).

**Screenshots**
![image](https://user-images.githubusercontent.com/6673842/83636978-2493aa00-a5a7-11ea-9650-0d951271f8e9.png)

**Additional context**
Add any other context about the problem here. For example, attach any useful logs related to the issue.

**Comment by pabloFuente** [comment]
OpenVidu 2.14.0 works fine when deploying On Premises. This is not a bug, this is a problem you have with your specific deployment. In other words: this is not a bug or an issue that belongs to the GitHub issue tracker, but a support question regarding your very own deployment.

You can open a new entry in OpenVidu public forum to get support: https://openvidu.discourse.group/

Regards.

**Comment by micaelgallego** [comment]
We have found problems with OpenVidu deployment in certain deployments.

We plan to release 2.15 version the next week with those problems fixed. Please try again when it is published.
