### ISSUE TITLE
mvn exec:java in openvidu-server will have permission denied error

### ISSUE THREAD

**Issue by ftntming** [OpenVidu/openvidu#507]
**Describe the bug**
As a NON-root user
git clone the openvidu project
cd openvidu-server
mvn install
then 
mvn exec:java
will see error "java.net.SocketException: Permission denied"

**My current workaround.**
cd target
sudo java -jar openvidu-server-2.15.0.jar

**Expected behavior**
openvidu-server starts and https://localhost:4443 is available.

**Wrong current behavior**
Error shows and https://localhost:4443 is NOT available

**OpenVidu tutorial where to replicate the error**
As a NON-root user
1. Clone repository 
2. cd openvidu-server
3. Compile the application like this "mvn install"
4. mvn exec:java
5. See error "java.net.SocketException: Permission denied"

**OpenVidu deployment info**
No need to deploy. Trying to compile and run openvidu-server from source code.

> **IMPORTANT NOTE**: please, if you think the bug might be related to OpenVidu Server side, specify here if you are also getting the error by using OpenVidu Server Demos instance. This instance is publicly available (use it only for this test, because it is not secure!!!): **URL**: `https://demos.openvidu.io:4443`, **SECRET**: `MY_SECRET`

**Client device info (if applicable)**
Ubuntu 18.04

**Screenshots**
N/A

**Additional context**
[ERROR] 2020-07-10 21:44:51,026 [io.openvidu.server.OpenViduServer.main()] org.springframework.boot.SpringApplication - Application run failed
org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:215)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer(ServletWebServerApplicationContext.java:297)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:163)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at io.openvidu.server.OpenViduServer.main(OpenViduServer.java:252)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: standardService.connector.startFailed
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:231)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors(TomcatWebServer.java:278)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start(TomcatWebServer.java:197)
	... 16 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Protocol handler start failed
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1008)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:227)
	... 18 common frames omitted
Caused by: java.net.SocketException: Permission denied
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85)
	at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:229)
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:212)
	at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1141)
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1227)
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:586)
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1005)
	... 20 common frames omitted
[INFO] 2020-07-10 21:44:51,028 [io.openvidu.server.OpenViduServer.main()] org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor - Shutting down ExecutorService 'applicationTaskExecutor'
[INFO] 2020-07-10 21:44:51,029 [io.openvidu.server.OpenViduServer.main()] org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler - Shutting down ExecutorService 'jsonrpcTaskScheduler'
[INFO] 2020-07-10 21:44:51,029 [io.openvidu.server.OpenViduServer.main()] org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler - Shutting down ExecutorService 'jsonrpcTaskScheduler'
[INFO] 2020-07-10 21:44:51,029 [io.openvidu.server.OpenViduServer.main()] io.openvidu.server.core.SessionManager - Closing all sessions
[INFO] 2020-07-10 21:44:51,029 [io.openvidu.server.OpenViduServer.main()] io.openvidu.server.kurento.kms.KmsManager - Closing all KurentoClients
[WARN] 2020-07-10 21:44:51,032 [io.openvidu.server.OpenViduServer.main()] org.kurento.jsonrpc.client.AbstractJsonRpcClientWebSocket - [KurentoClient]  Exception sending close message. org.kurento.jsonrpc.JsonRpcErrorException:'params' is requiered. Code: -32602. Data: {"type":"INVALID_PARAMS"}
[INFO] 2020-07-10 21:44:51,032 [AbstractJsonRpcClientWebSocket-reqResEventExec-e2-t0] io.openvidu.server.kurento.kms.KmsManager - Kurento Client "disconnected" event for KMS ws://localhost:8888/kurento [org.kurento.client.KurentoClient@97da315]. Closed explicitly
[INFO] 2020-07-10 21:44:51,033 [nioEventLoopGroup-2-1] org.kurento.jsonrpc.client.JsonRpcClientNettyWebSocket - [KurentoClient]  channel closed
[INFO] 2020-07-10 21:44:51,033 [AbstractJsonRpcClientWebSocket-reqResEventExec-e2-t0] io.openvidu.server.kurento.kms.KmsManager - Kurento Client "disconnected" event for KMS ws://localhost:8888/kurento [org.kurento.client.KurentoClient@97da315]. Closed explicitly
[WARN] 2020-07-10 21:44:51,036 [io.openvidu.server.OpenViduServer.main()] org.kurento.jsonrpc.client.AbstractJsonRpcClientWebSocket - [KurentoClient]  Exception sending close message. org.kurento.jsonrpc.JsonRpcClientClosedException:Trying to send a message in a client closed explicitly. When a client is closed, it can't be reused. It is necessary to create another one
[WARN] 2020-07-10 21:44:51,037 [io.openvidu.server.OpenViduServer.main()] org.kurento.jsonrpc.client.JsonRpcClientNettyWebSocket - [KurentoClient]  Trying to close a JsonRpcClientNettyWebSocket with channel == null
[WARN] 2020-07-10 21:44:51,037 [io.openvidu.server.OpenViduServer.main()] org.kurento.jsonrpc.client.JsonRpcClientNettyWebSocket - [KurentoClient]  Trying to close a JsonRpcClientNettyWebSocket with group == null
[INFO] 2020-07-10 21:44:51,037 [AbstractJsonRpcClientWebSocket-reqResEventExec-e4-t0] io.openvidu.server.kurento.kms.KmsManager - Kurento Client "disconnected" event for KMS ws://localhost:8888/kurento [org.kurento.client.KurentoClient@97da315]. Closed explicitly
[WARNING] 
org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat server
    at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start (TomcatWebServer.java:215)
    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer (ServletWebServerApplicationContext.java:297)
    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh (ServletWebServerApplicationContext.java:163)
    at org.springframework.context.support.AbstractApplicationContext.refresh (AbstractApplicationContext.java:553)
    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh (ServletWebServerApplicationContext.java:141)
    at org.springframework.boot.SpringApplication.refresh (SpringApplication.java:747)
    at org.springframework.boot.SpringApplication.refreshContext (SpringApplication.java:397)
    at org.springframework.boot.SpringApplication.run (SpringApplication.java:315)
    at org.springframework.boot.SpringApplication.run (SpringApplication.java:1226)
    at org.springframework.boot.SpringApplication.run (SpringApplication.java:1215)
    at io.openvidu.server.OpenViduServer.main (OpenViduServer.java:252)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:282)
    at java.lang.Thread.run (Thread.java:748)
Caused by: java.lang.IllegalArgumentException: standardService.connector.startFailed
    at org.apache.catalina.core.StandardService.addConnector (StandardService.java:231)
    at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors (TomcatWebServer.java:278)
    at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start (TomcatWebServer.java:197)
    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer (ServletWebServerApplicationContext.java:297)
    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh (ServletWebServerApplicationContext.java:163)
    at org.springframework.context.support.AbstractApplicationContext.refresh (AbstractApplicationContext.java:553)
    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh (ServletWebServerApplicationContext.java:141)
    at org.springframework.boot.SpringApplication.refresh (SpringApplication.java:747)
    at org.springframework.boot.SpringApplication.refreshContext (SpringApplication.java:397)
    at org.springframework.boot.SpringApplication.run (SpringApplication.java:315)
    at org.springframework.boot.SpringApplication.run (SpringApplication.java:1226)
    at org.springframework.boot.SpringApplication.run (SpringApplication.java:1215)
    at io.openvidu.server.OpenViduServer.main (OpenViduServer.java:252)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:282)
    at java.lang.Thread.run (Thread.java:748)
Caused by: org.apache.catalina.LifecycleException: Protocol handler start failed
    at org.apache.catalina.connector.Connector.startInternal (Connector.java:1008)
    at org.apache.catalina.util.LifecycleBase.start (LifecycleBase.java:183)
    at org.apache.catalina.core.StandardService.addConnector (StandardService.java:227)
    at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors (TomcatWebServer.java:278)
    at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start (TomcatWebServer.java:197)
    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer (ServletWebServerApplicationContext.java:297)
    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh (ServletWebServerApplicationContext.java:163)
    at org.springframework.context.support.AbstractApplicationContext.refresh (AbstractApplicationContext.java:553)
    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh (ServletWebServerApplicationContext.java:141)
    at org.springframework.boot.SpringApplication.refresh (SpringApplication.java:747)
    at org.springframework.boot.SpringApplication.refreshContext (SpringApplication.java:397)
    at org.springframework.boot.SpringApplication.run (SpringApplication.java:315)
    at org.springframework.boot.SpringApplication.run (SpringApplication.java:1226)
    at org.springframework.boot.SpringApplication.run (SpringApplication.java:1215)
    at io.openvidu.server.OpenViduServer.main (OpenViduServer.java:252)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:282)
    at java.lang.Thread.run (Thread.java:748)
Caused by: java.net.SocketException: Permission denied
    at sun.nio.ch.Net.bind0 (Native Method)
    at sun.nio.ch.Net.bind (Net.java:433)
    at sun.nio.ch.Net.bind (Net.java:425)
    at sun.nio.ch.ServerSocketChannelImpl.bind (ServerSocketChannelImpl.java:220)
    at sun.nio.ch.ServerSocketAdaptor.bind (ServerSocketAdaptor.java:85)
    at org.apache.tomcat.util.net.NioEndpoint.initServerSocket (NioEndpoint.java:229)
    at org.apache.tomcat.util.net.NioEndpoint.bind (NioEndpoint.java:212)
    at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup (AbstractEndpoint.java:1141)
    at org.apache.tomcat.util.net.AbstractEndpoint.start (AbstractEndpoint.java:1227)
    at org.apache.coyote.AbstractProtocol.start (AbstractProtocol.java:586)
    at org.apache.catalina.connector.Connector.startInternal (Connector.java:1005)
    at org.apache.catalina.util.LifecycleBase.start (LifecycleBase.java:183)
    at org.apache.catalina.core.StandardService.addConnector (StandardService.java:227)
    at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.addPreviouslyRemovedConnectors (TomcatWebServer.java:278)
    at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.start (TomcatWebServer.java:197)
    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.startWebServer (ServletWebServerApplicationContext.java:297)
    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh (ServletWebServerApplicationContext.java:163)
    at org.springframework.context.support.AbstractApplicationContext.refresh (AbstractApplicationContext.java:553)
    at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh (ServletWebServerApplicationContext.java:141)
    at org.springframework.boot.SpringApplication.refresh (SpringApplication.java:747)
    at org.springframework.boot.SpringApplication.refreshContext (SpringApplication.java:397)
    at org.springframework.boot.SpringApplication.run (SpringApplication.java:315)
    at org.springframework.boot.SpringApplication.run (SpringApplication.java:1226)
    at org.springframework.boot.SpringApplication.run (SpringApplication.java:1215)
    at io.openvidu.server.OpenViduServer.main (OpenViduServer.java:252)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:282)
    at java.lang.Thread.run (Thread.java:748)

**Comment by pabloFuente** [comment]
If you want to run openvidu-server in your local setup, do it like stated in these instructions: https://docs.openvidu.io/en/2.15.0/developing/#example-setup-for-development

**Comment by ftntming** [comment]
> If you want to run openvidu-server in your local setup, do it like stated in these instructions: https://docs.openvidu.io/en/2.15.0/developing/#example-setup-for-development

Hi Pablo,
Thanks for the pointer. I did started it correctly using HTTPS_PORT=4443, that's only thing my .env file is missing.
I don't know why it failed to start at port 443 since no other application is taking that port. I added "HTTPS_PORT=4443" to my .env and "mvn exec:java" now works.
Cheers,
Ming

**Comment by pabloFuente** [comment]
It fails because in Ubuntu port 443 is protected and only able to be used by a root process.

**Comment by ftntming** [comment]
Hi @pabloFuente , any chance this issue https://github.com/OpenVidu/openvidu-tutorials/issues/117 will be looked at?

**Comment by pabloFuente** [comment]
That's also not an issue. Please, read carefully how to launch openvidu with recording module enabled. OpenVidu Java Client documentation also states what 501 status means (recording module not enabled).
