### ISSUE TITLE
Openvidu java client bugs

### ISSUE THREAD

**Issue by hanhfgia** [OpenVidu/openvidu#509]
# test openvidu-ipcamera tutorial
Subcribe ipcameras to show video. it's ok. Close browser without unsubcribe. Re-open browser with `https://localhost:8080/?credentials=PASSWORD`. Got bugs as below.

Someone guides me to fix? thanks

**Describe the bug**
```
2020-07-16 14:24:26.590  INFO 38635 --- [io-8080-exec-10] io.openvidu.java.client.OpenVidu         : New session 'MySurveillanceSession123' fetched
2020-07-16 14:24:26.592 ERROR 38635 --- [io-8080-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
	at io.openvidu.java.client.Session.lambda$resetSessionWithJson$3(Session.java:555) ~[openvidu-java-client-2.15.0.jar:na]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_221]
	at io.openvidu.java.client.Session.resetSessionWithJson(Session.java:531) ~[openvidu-java-client-2.15.0.jar:na]
	at io.openvidu.java.client.Session.<init>(Session.java:69) ~[openvidu-java-client-2.15.0.jar:na]
	at io.openvidu.java.client.OpenVidu.lambda$null$2(OpenVidu.java:568) ~[openvidu-java-client-2.15.0.jar:na]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_221]
	at io.openvidu.java.client.OpenVidu.lambda$fetch$3(OpenVidu.java:565) ~[openvidu-java-client-2.15.0.jar:na]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_221]
	at io.openvidu.java.client.OpenVidu.fetch(OpenVidu.java:553) ~[openvidu-java-client-2.15.0.jar:na]
	at io.openvidu.ipcameras.MyRestController.createOpenViduSession(MyRestController.java:97) ~[classes/:na]
	at io.openvidu.ipcameras.MyRestController.subscribe(MyRestController.java:62) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_221]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.0.RELEASE.jar:5.2.0.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.0.RELEASE.jar:5.2.0.RELEASE]
```

**Comment by pabloFuente** [comment]
Please, if this is still a problem for your, re-open this issue at openvidu-tutorials repo, where it belongs: https://github.com/OpenVidu/openvidu-tutorials/issues

It must be something weong at the tutorial backend side, not at openvidu-server or openvidu-java-client.
