### ISSUE TITLE
Can not import module after upgrage 2.16 openvidu-node-client

### ISSUE THREAD

**Issue by rikser123** [OpenVidu/openvidu#558]
After upgrade module i have error
Error: Cannot find module 'D:\Projects\currento\node_modules\openvidu-node-client\lib\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:303:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\Projects\currento\app.js:2:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'D:\\Projects\\currento\\node_modules\\openvidu-node-client\\package.json',
  requestPath: 'openvidu-node-client'
}
[nodemon] app crashed - waiting for file changes before starting...

lib folder dont contain index.js, ony index.js.map

**Comment by pabloFuente** [comment]
I don't know what the problem may be. Try running openvidu-js-node tutorial, which is using openvidu-node-client 2.16.0: https://docs.openvidu.io/en/2.16.0/tutorials/openvidu-js-node/#running-this-tutorial
As you will see it works just fine.
