### ISSUE TITLE
Unable access recordings from inspector after upgrading to v2.17.0

### ISSUE THREAD

**Issue by raghuk-botaiml** [OpenVidu/openvidu#615]
I just upgraded to v2.17.0 and made all the necessary changes to the .env file. But I am unable to access recordings from inspector anymore.

**Expected behavior**
Inspector should display all the recordings and allow me to play/download/delete the recordings.

**Wrong current behavior**
Inspector's recording tab keeps showing the loading animation and never finishes.

OpenVidu Pro Server log shows the following exception:

```
openvidu-server_1  | [ERROR] 2021-03-10 21:17:23,411 [http-nio-0.0.0.0-5443-exec-4] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
openvidu-server_1  | java.lang.NullPointerException: null
openvidu-server_1  |    at io.openvidu.server.recording.Recording.<init>(Recording.java:61)
openvidu-server_1  |    at io.openvidu.server.recording.service.RecordingManager.getRecordingFromJson(RecordingManager.java:620)
openvidu-server_1  |    at io.openvidu.server.recording.service.RecordingManager.getRecordingFromEntityFile(RecordingManager.java:614)
openvidu-server_1  |    at io.openvidu.server.recording.service.RecordingManager.getAllRecordingsFromLocalStorage(RecordingManager.java:595)
openvidu-server_1  |    at io.openvidu.server.recording.service.RecordingManagerUtilsLocalStorage.getAllRecordingsFromStorage(RecordingManagerUtilsLocalStorage.java:27)
openvidu-server_1  |    at io.openvidu.server.recording.service.RecordingManager.getAllRecordings(RecordingManager.java:512)
openvidu-server_1  |    at io.openvidu.server.rest.SessionRestController.listRecordings(SessionRestController.java:471)
openvidu-server_1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
openvidu-server_1  |    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
openvidu-server_1  |    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
openvidu-server_1  |    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
openvidu-server_1  |    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
openvidu-server_1  |    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
openvidu-server_1  |    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
openvidu-server_1  |    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
openvidu-server_1  |    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
openvidu-server_1  |    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
openvidu-server_1  |    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
openvidu-server_1  |    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
openvidu-server_1  |    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
openvidu-server_1  |    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
openvidu-server_1  |    at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
openvidu-server_1  |    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
openvidu-server_1  |    at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
openvidu-server_1  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
openvidu-server_1  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
openvidu-server_1  |    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
openvidu-server_1  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
openvidu-server_1  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
openvidu-server_1  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:113)
openvidu-server_1  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
openvidu-server_1  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
openvidu-server_1  |    at io.openvidu.server.rest.ApiRestPathRewriteFilter.doFilter(ApiRestPathRewriteFilter.java:115)
openvidu-server_1  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
openvidu-server_1  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
openvidu-server_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
openvidu-server_1  |    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
openvidu-server_1  |    at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
openvidu-server_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
openvidu-server_1  |    at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
openvidu-server_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
openvidu-server_1  |    at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
openvidu-server_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
openvidu-server_1  |    at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
openvidu-server_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
openvidu-server_1  |    at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
openvidu-server_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
openvidu-server_1  |    at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
openvidu-server_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
openvidu-server_1  |    at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:204)
openvidu-server_1  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
openvidu-server_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
openvidu-server_1  |    at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
openvidu-server_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
openvidu-server_1  |    at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92)
openvidu-server_1  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
openvidu-server_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
openvidu-server_1  |    at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
openvidu-server_1  |    at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
openvidu-server_1  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
openvidu-server_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
openvidu-server_1  |    at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
openvidu-server_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
openvidu-server_1  |    at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
openvidu-server_1  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
openvidu-server_1  |    at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
openvidu-server_1  |    at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
openvidu-server_1  |    at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
openvidu-server_1  |    at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
openvidu-server_1  |    at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
openvidu-server_1  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
openvidu-server_1  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
openvidu-server_1  |    at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
openvidu-server_1  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
openvidu-server_1  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
openvidu-server_1  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
openvidu-server_1  |    at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
openvidu-server_1  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
openvidu-server_1  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
openvidu-server_1  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
openvidu-server_1  |    at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
openvidu-server_1  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
openvidu-server_1  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
openvidu-server_1  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
openvidu-server_1  |    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
openvidu-server_1  |    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
openvidu-server_1  |    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
openvidu-server_1  |    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
openvidu-server_1  |    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
openvidu-server_1  |    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
openvidu-server_1  |    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
openvidu-server_1  |    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
openvidu-server_1  |    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
openvidu-server_1  |    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
openvidu-server_1  |    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
openvidu-server_1  |    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
openvidu-server_1  |    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
openvidu-server_1  |    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
openvidu-server_1  |    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
openvidu-server_1  |    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
openvidu-server_1  |    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
openvidu-server_1  |    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
openvidu-server_1  |    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
openvidu-server_1  |    at java.base/java.lang.Thread.run(Thread.java:834)
```

**OpenVidu deployment info**
- Azure deployment using On Premise method as explained in OpenVidu Docs (https://docs.openvidu.io/en/2.17.0/openvidu-pro/deployment/on-premises/#2-openvidu-server-pro-node)

**Screenshots**
![image](https://user-images.githubusercontent.com/64590389/110699647-16994680-8215-11eb-961e-8d0e4cfc99ea.png)

**Comment by pabloFuente** [comment]
There has been an unexpected breaking change from version 2.16.0 to 2.17.0, making 2.16.0 recordings incompatible.
We are working on a fix for it. Probably a simple script that after execution will fix old recordings to be compatible with 2.17.0.

**Comment by pabloFuente** [comment]
[restoreOldRecordings.txt](https://github.com/OpenVidu/openvidu/files/6122499/restoreOldRecordings.txt)

This bash script will fix your old recordings. Place it in your OpenVidu Server node recordings folder (by default **`/opt/openvidu/recordings`**) and run:

```bash
# If you haven't do so yet, first rename the file from txt to a bash script
mv restoreOldRecordings.txt restoreOldRecordings.sh

# Give execution permissions
sudo chmod 777 restoreOldRecordings.sh

# Run the script
./restoreOldRecordings.sh
```

**Comment by pabloFuente** [comment]
We are also releasing a new 2.17.1 version of [openvidu-server](https://hub.docker.com/r/openvidu/openvidu-server) and [openvidu-server-pro](https://hub.docker.com/r/openvidu/openvidu-server-pro) images with a fix for this issue.

**Comment by pabloFuente** [comment]
As a final solution to this problem **(as a reminder: recordings 2.16.0 and below not compatible with OpenVidu 2.17.0)**, there is a new patch release. To use it, modifiy **`docker-compose.yml`** file of your OpenVidu deployment (by default at path **`/opt/openvidu/docker-compose.yml`**) and change the tag value of...

 In OpenVidu CE ([this line](https://github.com/OpenVidu/openvidu/blob/master/openvidu-server/deployments/ce/docker-compose/docker-compose.yml#L25)):
```
image: openvidu/openvidu-server:2.17.0
```

to

```
image: openvidu/openvidu-server:2.17.1
```

And in OpenVidu PRO ([this line](https://github.com/OpenVidu/openvidu/blob/master/openvidu-server/deployments/pro/docker-compose/openvidu-server-pro/docker-compose.yml#L25)):
```
image: openvidu/openvidu-server-pro:2.17.0
```

to

```
image: openvidu/openvidu-server-pro:2.17.1
```

**Comment by raghuk-botaiml** [comment]
Thanks for the quick resolution. That worked.
