### ISSUE TITLE
Recording not working after upgrading to v2.17.0

### ISSUE THREAD

**Issue by raghuk-botaiml** [OpenVidu/openvidu#617]
After upgrading to v.2.17.0 recording is not working at all. I am getting the following error in openvidu server logs:

```
8306230bec46d18d5df18fdf22e696.jpg
openvidu-server_1  | Exception in thread "Thread-10" io.openvidu.client.OpenViduException: Couldn't initialize recording container. Error: Read timed out. Code: 703
openvidu-server_1  |    at io.openvidu.server.recording.service.RecordingService.failStartRecording(RecordingService.java:201)
openvidu-server_1  |    at io.openvidu.server.recording.service.ComposedRecordingService.startRecordingWithVideo(ComposedRecordingService.java:190)
openvidu-server_1  |    at io.openvidu.server.recording.service.ComposedRecordingService.startRecording(ComposedRecordingService.java:93)
openvidu-server_1  |    at io.openvidu.server.recording.service.RecordingManager.startRecording(RecordingManager.java:288)
openvidu-server_1  |    at io.openvidu.server.kurento.core.KurentoSessionManager.lambda$publishVideo$0(KurentoSessionManager.java:458)
openvidu-server_1  | [INFO] 2021-03-14 18:13:31,141 [Thread-12] io.openvidu.server.pro.recording.MedianNodeRecordingDownloader - File http://10.1.27.4:3000/media-node/recordings/7a8306230bec46d18d5df18fdf22e696/7a8306230bec46d18d5df18fdf22e696.mp4 is 0 KB in size
openvidu-server_1  |    at java.base/java.lang.Thread.run(Thread.java:834)
```

I have the following settings related to recording in .env file:
```
OPENVIDU_PRO_RECORDING_STORAGE=local
OPENVIDU_RECORDING=true
OPENVIDU_RECORDING_DEBUG=false
OPENVIDU_RECORDING_PATH=/data/openvidu/recordings/
OPENVIDU_RECORDING_CUSTOM_LAYOUT=/opt/openvidu/custom-layout
OPENVIDU_RECORDING_PUBLIC_ACCESS=false
OPENVIDU_RECORDING_NOTIFICATION=publisher_moderator
OPENVIDU_RECORDING_AUTOSTOP_TIMEOUT=60
```

To be sure, I event stopped the docker images and removed all the images and freshly redeployed the media node by following the steps at https://docs.openvidu.io/en/2.17.0/openvidu-pro/deployment/on-premises/#31-deployment

This issue is critical because I have a demo coming up and I am stuck due to this. Hope this can be resolved soon with your help.

Thanks,
Raghu

**Comment by micaelgallego** [comment]
If you are in a hurry, test with 2.16 version.

Please can you share with us the media node controller logs?

**Comment by raghuk-botaiml** [comment]
Closing this issue as I do not have the environment to recreate the bug anymore. I have destroyed the environment and created a new v2.17 one with no old data. It is all working fine now.
