### ISSUE TITLE
Cannot read property 'outboundStreamOpts' of undefined

### ISSUE THREAD

**Issue by amirito** [OpenVidu/openvidu#640]
**Describe the bug**
I am using openvidu-react-native-adapter in my project and some devices are getting crashed
I used logcat to see the problem and I faced this error: 

``` 
FATAL EXCEPTION: mqt_native_modules
Process: "MY APP PACKAGE", PID: 30017
com.facebook.react.common.c: TypeError: Cannot read property 'outboundStreamOpts' of undefined, js engine: hermes, stack:
anonymous@1:1512954
anonymous@1:1492591
value@1:1548509
anonymous@1:1546739
value@1:79274
value@1:89381
anonymous@1:87861
value@1:88826
value@1:87819
 
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(Unknown Source:134)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:149)
 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:21)
 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
 	at android.os.Handler.handleCallback(Handler.java:873)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
	at android.os.Looper.loop(Looper.java:214)
 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(Unknown Source:37)
 	at java.lang.Thread.run(Thread.java:764)


```

**Expected behavior**
in some devices it works fine, but in some doesn't
for example "Samsung Galaxy Tab A 10.1 2019 LTE"

**Wrong current behavior**
I don't even have `outboundStreamOpts` in my code but I got this exception in logcat when I use `adb logcat -b crash #default`

And I found out that this is an option in openvidu

**Comment by amirito** [comment]
I should say I used 
`npx metro-symbolicate android/app/build/generated/sourcemaps/react/release/index.android.bundle.map < stacktrace.txt` 
and now the the logcat is more understandable 

this is where my app crashes:
```
/node_modules/openvidu-browser/lib/OpenVidu/Stream.js:78:<global>
```
and this is what is in OpenVidu/Stream.js:78
```js
var logger = OpenViduLogger_1.OpenViduLogger.getInstance();
```

Can anyone help me solve this?
